// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package shipment

//go:generate minimock -i github.com/bazeeko/vektor-shipment/internal/services/shipment.PricingService -o pricing_service_mock_test.go -n PricingServiceMock -p shipment

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	pricingservice "github.com/bazeeko/vektor-shipment/internal/services/pricing"
	"github.com/gojuno/minimock/v3"
)

// PricingServiceMock implements PricingService
type PricingServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCalculateShipmentCost          func() (c1 pricingservice.Cost, err error)
	funcCalculateShipmentCostOrigin    string
	inspectFuncCalculateShipmentCost   func()
	afterCalculateShipmentCostCounter  uint64
	beforeCalculateShipmentCostCounter uint64
	CalculateShipmentCostMock          mPricingServiceMockCalculateShipmentCost
}

// NewPricingServiceMock returns a mock for PricingService
func NewPricingServiceMock(t minimock.Tester) *PricingServiceMock {
	m := &PricingServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CalculateShipmentCostMock = mPricingServiceMockCalculateShipmentCost{mock: m}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mPricingServiceMockCalculateShipmentCost struct {
	optional           bool
	mock               *PricingServiceMock
	defaultExpectation *PricingServiceMockCalculateShipmentCostExpectation
	expectations       []*PricingServiceMockCalculateShipmentCostExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// PricingServiceMockCalculateShipmentCostExpectation specifies expectation struct of the PricingService.CalculateShipmentCost
type PricingServiceMockCalculateShipmentCostExpectation struct {
	mock *PricingServiceMock

	results      *PricingServiceMockCalculateShipmentCostResults
	returnOrigin string
	Counter      uint64
}

// PricingServiceMockCalculateShipmentCostResults contains results of the PricingService.CalculateShipmentCost
type PricingServiceMockCalculateShipmentCostResults struct {
	c1  pricingservice.Cost
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCalculateShipmentCost *mPricingServiceMockCalculateShipmentCost) Optional() *mPricingServiceMockCalculateShipmentCost {
	mmCalculateShipmentCost.optional = true
	return mmCalculateShipmentCost
}

// Expect sets up expected params for PricingService.CalculateShipmentCost
func (mmCalculateShipmentCost *mPricingServiceMockCalculateShipmentCost) Expect() *mPricingServiceMockCalculateShipmentCost {
	if mmCalculateShipmentCost.mock.funcCalculateShipmentCost != nil {
		mmCalculateShipmentCost.mock.t.Fatalf("PricingServiceMock.CalculateShipmentCost mock is already set by Set")
	}

	if mmCalculateShipmentCost.defaultExpectation == nil {
		mmCalculateShipmentCost.defaultExpectation = &PricingServiceMockCalculateShipmentCostExpectation{}
	}

	return mmCalculateShipmentCost
}

// Inspect accepts an inspector function that has same arguments as the PricingService.CalculateShipmentCost
func (mmCalculateShipmentCost *mPricingServiceMockCalculateShipmentCost) Inspect(f func()) *mPricingServiceMockCalculateShipmentCost {
	if mmCalculateShipmentCost.mock.inspectFuncCalculateShipmentCost != nil {
		mmCalculateShipmentCost.mock.t.Fatalf("Inspect function is already set for PricingServiceMock.CalculateShipmentCost")
	}

	mmCalculateShipmentCost.mock.inspectFuncCalculateShipmentCost = f

	return mmCalculateShipmentCost
}

// Return sets up results that will be returned by PricingService.CalculateShipmentCost
func (mmCalculateShipmentCost *mPricingServiceMockCalculateShipmentCost) Return(c1 pricingservice.Cost, err error) *PricingServiceMock {
	if mmCalculateShipmentCost.mock.funcCalculateShipmentCost != nil {
		mmCalculateShipmentCost.mock.t.Fatalf("PricingServiceMock.CalculateShipmentCost mock is already set by Set")
	}

	if mmCalculateShipmentCost.defaultExpectation == nil {
		mmCalculateShipmentCost.defaultExpectation = &PricingServiceMockCalculateShipmentCostExpectation{mock: mmCalculateShipmentCost.mock}
	}
	mmCalculateShipmentCost.defaultExpectation.results = &PricingServiceMockCalculateShipmentCostResults{c1, err}
	mmCalculateShipmentCost.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCalculateShipmentCost.mock
}

// Set uses given function f to mock the PricingService.CalculateShipmentCost method
func (mmCalculateShipmentCost *mPricingServiceMockCalculateShipmentCost) Set(f func() (c1 pricingservice.Cost, err error)) *PricingServiceMock {
	if mmCalculateShipmentCost.defaultExpectation != nil {
		mmCalculateShipmentCost.mock.t.Fatalf("Default expectation is already set for the PricingService.CalculateShipmentCost method")
	}

	if len(mmCalculateShipmentCost.expectations) > 0 {
		mmCalculateShipmentCost.mock.t.Fatalf("Some expectations are already set for the PricingService.CalculateShipmentCost method")
	}

	mmCalculateShipmentCost.mock.funcCalculateShipmentCost = f
	mmCalculateShipmentCost.mock.funcCalculateShipmentCostOrigin = minimock.CallerInfo(1)
	return mmCalculateShipmentCost.mock
}

// Times sets number of times PricingService.CalculateShipmentCost should be invoked
func (mmCalculateShipmentCost *mPricingServiceMockCalculateShipmentCost) Times(n uint64) *mPricingServiceMockCalculateShipmentCost {
	if n == 0 {
		mmCalculateShipmentCost.mock.t.Fatalf("Times of PricingServiceMock.CalculateShipmentCost mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCalculateShipmentCost.expectedInvocations, n)
	mmCalculateShipmentCost.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCalculateShipmentCost
}

func (mmCalculateShipmentCost *mPricingServiceMockCalculateShipmentCost) invocationsDone() bool {
	if len(mmCalculateShipmentCost.expectations) == 0 && mmCalculateShipmentCost.defaultExpectation == nil && mmCalculateShipmentCost.mock.funcCalculateShipmentCost == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCalculateShipmentCost.mock.afterCalculateShipmentCostCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCalculateShipmentCost.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CalculateShipmentCost implements PricingService
func (mmCalculateShipmentCost *PricingServiceMock) CalculateShipmentCost() (c1 pricingservice.Cost, err error) {
	mm_atomic.AddUint64(&mmCalculateShipmentCost.beforeCalculateShipmentCostCounter, 1)
	defer mm_atomic.AddUint64(&mmCalculateShipmentCost.afterCalculateShipmentCostCounter, 1)

	mmCalculateShipmentCost.t.Helper()

	if mmCalculateShipmentCost.inspectFuncCalculateShipmentCost != nil {
		mmCalculateShipmentCost.inspectFuncCalculateShipmentCost()
	}

	if mmCalculateShipmentCost.CalculateShipmentCostMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCalculateShipmentCost.CalculateShipmentCostMock.defaultExpectation.Counter, 1)

		mm_results := mmCalculateShipmentCost.CalculateShipmentCostMock.defaultExpectation.results
		if mm_results == nil {
			mmCalculateShipmentCost.t.Fatal("No results are set for the PricingServiceMock.CalculateShipmentCost")
		}
		return (*mm_results).c1, (*mm_results).err
	}
	if mmCalculateShipmentCost.funcCalculateShipmentCost != nil {
		return mmCalculateShipmentCost.funcCalculateShipmentCost()
	}
	mmCalculateShipmentCost.t.Fatalf("Unexpected call to PricingServiceMock.CalculateShipmentCost.")
	return
}

// CalculateShipmentCostAfterCounter returns a count of finished PricingServiceMock.CalculateShipmentCost invocations
func (mmCalculateShipmentCost *PricingServiceMock) CalculateShipmentCostAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCalculateShipmentCost.afterCalculateShipmentCostCounter)
}

// CalculateShipmentCostBeforeCounter returns a count of PricingServiceMock.CalculateShipmentCost invocations
func (mmCalculateShipmentCost *PricingServiceMock) CalculateShipmentCostBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCalculateShipmentCost.beforeCalculateShipmentCostCounter)
}

// MinimockCalculateShipmentCostDone returns true if the count of the CalculateShipmentCost invocations corresponds
// the number of defined expectations
func (m *PricingServiceMock) MinimockCalculateShipmentCostDone() bool {
	if m.CalculateShipmentCostMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CalculateShipmentCostMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CalculateShipmentCostMock.invocationsDone()
}

// MinimockCalculateShipmentCostInspect logs each unmet expectation
func (m *PricingServiceMock) MinimockCalculateShipmentCostInspect() {
	for _, e := range m.CalculateShipmentCostMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to PricingServiceMock.CalculateShipmentCost")
		}
	}

	afterCalculateShipmentCostCounter := mm_atomic.LoadUint64(&m.afterCalculateShipmentCostCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CalculateShipmentCostMock.defaultExpectation != nil && afterCalculateShipmentCostCounter < 1 {
		m.t.Errorf("Expected call to PricingServiceMock.CalculateShipmentCost at\n%s", m.CalculateShipmentCostMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCalculateShipmentCost != nil && afterCalculateShipmentCostCounter < 1 {
		m.t.Errorf("Expected call to PricingServiceMock.CalculateShipmentCost at\n%s", m.funcCalculateShipmentCostOrigin)
	}

	if !m.CalculateShipmentCostMock.invocationsDone() && afterCalculateShipmentCostCounter > 0 {
		m.t.Errorf("Expected %d calls to PricingServiceMock.CalculateShipmentCost at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CalculateShipmentCostMock.expectedInvocations), m.CalculateShipmentCostMock.expectedInvocationsOrigin, afterCalculateShipmentCostCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *PricingServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCalculateShipmentCostInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *PricingServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *PricingServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCalculateShipmentCostDone()
}
