// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package shipment

//go:generate minimock -i github.com/bazeeko/vektor-shipment/internal/services/shipment.ReferenceGenerator -o reference_generator_mock_test.go -n ReferenceGeneratorMock -p shipment

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ReferenceGeneratorMock implements ReferenceGenerator
type ReferenceGeneratorMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGenerateReferenceNumber          func() (s1 string, err error)
	funcGenerateReferenceNumberOrigin    string
	inspectFuncGenerateReferenceNumber   func()
	afterGenerateReferenceNumberCounter  uint64
	beforeGenerateReferenceNumberCounter uint64
	GenerateReferenceNumberMock          mReferenceGeneratorMockGenerateReferenceNumber
}

// NewReferenceGeneratorMock returns a mock for ReferenceGenerator
func NewReferenceGeneratorMock(t minimock.Tester) *ReferenceGeneratorMock {
	m := &ReferenceGeneratorMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GenerateReferenceNumberMock = mReferenceGeneratorMockGenerateReferenceNumber{mock: m}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mReferenceGeneratorMockGenerateReferenceNumber struct {
	optional           bool
	mock               *ReferenceGeneratorMock
	defaultExpectation *ReferenceGeneratorMockGenerateReferenceNumberExpectation
	expectations       []*ReferenceGeneratorMockGenerateReferenceNumberExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ReferenceGeneratorMockGenerateReferenceNumberExpectation specifies expectation struct of the ReferenceGenerator.GenerateReferenceNumber
type ReferenceGeneratorMockGenerateReferenceNumberExpectation struct {
	mock *ReferenceGeneratorMock

	results      *ReferenceGeneratorMockGenerateReferenceNumberResults
	returnOrigin string
	Counter      uint64
}

// ReferenceGeneratorMockGenerateReferenceNumberResults contains results of the ReferenceGenerator.GenerateReferenceNumber
type ReferenceGeneratorMockGenerateReferenceNumberResults struct {
	s1  string
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGenerateReferenceNumber *mReferenceGeneratorMockGenerateReferenceNumber) Optional() *mReferenceGeneratorMockGenerateReferenceNumber {
	mmGenerateReferenceNumber.optional = true
	return mmGenerateReferenceNumber
}

// Expect sets up expected params for ReferenceGenerator.GenerateReferenceNumber
func (mmGenerateReferenceNumber *mReferenceGeneratorMockGenerateReferenceNumber) Expect() *mReferenceGeneratorMockGenerateReferenceNumber {
	if mmGenerateReferenceNumber.mock.funcGenerateReferenceNumber != nil {
		mmGenerateReferenceNumber.mock.t.Fatalf("ReferenceGeneratorMock.GenerateReferenceNumber mock is already set by Set")
	}

	if mmGenerateReferenceNumber.defaultExpectation == nil {
		mmGenerateReferenceNumber.defaultExpectation = &ReferenceGeneratorMockGenerateReferenceNumberExpectation{}
	}

	return mmGenerateReferenceNumber
}

// Inspect accepts an inspector function that has same arguments as the ReferenceGenerator.GenerateReferenceNumber
func (mmGenerateReferenceNumber *mReferenceGeneratorMockGenerateReferenceNumber) Inspect(f func()) *mReferenceGeneratorMockGenerateReferenceNumber {
	if mmGenerateReferenceNumber.mock.inspectFuncGenerateReferenceNumber != nil {
		mmGenerateReferenceNumber.mock.t.Fatalf("Inspect function is already set for ReferenceGeneratorMock.GenerateReferenceNumber")
	}

	mmGenerateReferenceNumber.mock.inspectFuncGenerateReferenceNumber = f

	return mmGenerateReferenceNumber
}

// Return sets up results that will be returned by ReferenceGenerator.GenerateReferenceNumber
func (mmGenerateReferenceNumber *mReferenceGeneratorMockGenerateReferenceNumber) Return(s1 string, err error) *ReferenceGeneratorMock {
	if mmGenerateReferenceNumber.mock.funcGenerateReferenceNumber != nil {
		mmGenerateReferenceNumber.mock.t.Fatalf("ReferenceGeneratorMock.GenerateReferenceNumber mock is already set by Set")
	}

	if mmGenerateReferenceNumber.defaultExpectation == nil {
		mmGenerateReferenceNumber.defaultExpectation = &ReferenceGeneratorMockGenerateReferenceNumberExpectation{mock: mmGenerateReferenceNumber.mock}
	}
	mmGenerateReferenceNumber.defaultExpectation.results = &ReferenceGeneratorMockGenerateReferenceNumberResults{s1, err}
	mmGenerateReferenceNumber.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGenerateReferenceNumber.mock
}

// Set uses given function f to mock the ReferenceGenerator.GenerateReferenceNumber method
func (mmGenerateReferenceNumber *mReferenceGeneratorMockGenerateReferenceNumber) Set(f func() (s1 string, err error)) *ReferenceGeneratorMock {
	if mmGenerateReferenceNumber.defaultExpectation != nil {
		mmGenerateReferenceNumber.mock.t.Fatalf("Default expectation is already set for the ReferenceGenerator.GenerateReferenceNumber method")
	}

	if len(mmGenerateReferenceNumber.expectations) > 0 {
		mmGenerateReferenceNumber.mock.t.Fatalf("Some expectations are already set for the ReferenceGenerator.GenerateReferenceNumber method")
	}

	mmGenerateReferenceNumber.mock.funcGenerateReferenceNumber = f
	mmGenerateReferenceNumber.mock.funcGenerateReferenceNumberOrigin = minimock.CallerInfo(1)
	return mmGenerateReferenceNumber.mock
}

// Times sets number of times ReferenceGenerator.GenerateReferenceNumber should be invoked
func (mmGenerateReferenceNumber *mReferenceGeneratorMockGenerateReferenceNumber) Times(n uint64) *mReferenceGeneratorMockGenerateReferenceNumber {
	if n == 0 {
		mmGenerateReferenceNumber.mock.t.Fatalf("Times of ReferenceGeneratorMock.GenerateReferenceNumber mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGenerateReferenceNumber.expectedInvocations, n)
	mmGenerateReferenceNumber.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGenerateReferenceNumber
}

func (mmGenerateReferenceNumber *mReferenceGeneratorMockGenerateReferenceNumber) invocationsDone() bool {
	if len(mmGenerateReferenceNumber.expectations) == 0 && mmGenerateReferenceNumber.defaultExpectation == nil && mmGenerateReferenceNumber.mock.funcGenerateReferenceNumber == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGenerateReferenceNumber.mock.afterGenerateReferenceNumberCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGenerateReferenceNumber.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GenerateReferenceNumber implements ReferenceGenerator
func (mmGenerateReferenceNumber *ReferenceGeneratorMock) GenerateReferenceNumber() (s1 string, err error) {
	mm_atomic.AddUint64(&mmGenerateReferenceNumber.beforeGenerateReferenceNumberCounter, 1)
	defer mm_atomic.AddUint64(&mmGenerateReferenceNumber.afterGenerateReferenceNumberCounter, 1)

	mmGenerateReferenceNumber.t.Helper()

	if mmGenerateReferenceNumber.inspectFuncGenerateReferenceNumber != nil {
		mmGenerateReferenceNumber.inspectFuncGenerateReferenceNumber()
	}

	if mmGenerateReferenceNumber.GenerateReferenceNumberMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGenerateReferenceNumber.GenerateReferenceNumberMock.defaultExpectation.Counter, 1)

		mm_results := mmGenerateReferenceNumber.GenerateReferenceNumberMock.defaultExpectation.results
		if mm_results == nil {
			mmGenerateReferenceNumber.t.Fatal("No results are set for the ReferenceGeneratorMock.GenerateReferenceNumber")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmGenerateReferenceNumber.funcGenerateReferenceNumber != nil {
		return mmGenerateReferenceNumber.funcGenerateReferenceNumber()
	}
	mmGenerateReferenceNumber.t.Fatalf("Unexpected call to ReferenceGeneratorMock.GenerateReferenceNumber.")
	return
}

// GenerateReferenceNumberAfterCounter returns a count of finished ReferenceGeneratorMock.GenerateReferenceNumber invocations
func (mmGenerateReferenceNumber *ReferenceGeneratorMock) GenerateReferenceNumberAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGenerateReferenceNumber.afterGenerateReferenceNumberCounter)
}

// GenerateReferenceNumberBeforeCounter returns a count of ReferenceGeneratorMock.GenerateReferenceNumber invocations
func (mmGenerateReferenceNumber *ReferenceGeneratorMock) GenerateReferenceNumberBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGenerateReferenceNumber.beforeGenerateReferenceNumberCounter)
}

// MinimockGenerateReferenceNumberDone returns true if the count of the GenerateReferenceNumber invocations corresponds
// the number of defined expectations
func (m *ReferenceGeneratorMock) MinimockGenerateReferenceNumberDone() bool {
	if m.GenerateReferenceNumberMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GenerateReferenceNumberMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GenerateReferenceNumberMock.invocationsDone()
}

// MinimockGenerateReferenceNumberInspect logs each unmet expectation
func (m *ReferenceGeneratorMock) MinimockGenerateReferenceNumberInspect() {
	for _, e := range m.GenerateReferenceNumberMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to ReferenceGeneratorMock.GenerateReferenceNumber")
		}
	}

	afterGenerateReferenceNumberCounter := mm_atomic.LoadUint64(&m.afterGenerateReferenceNumberCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GenerateReferenceNumberMock.defaultExpectation != nil && afterGenerateReferenceNumberCounter < 1 {
		m.t.Errorf("Expected call to ReferenceGeneratorMock.GenerateReferenceNumber at\n%s", m.GenerateReferenceNumberMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGenerateReferenceNumber != nil && afterGenerateReferenceNumberCounter < 1 {
		m.t.Errorf("Expected call to ReferenceGeneratorMock.GenerateReferenceNumber at\n%s", m.funcGenerateReferenceNumberOrigin)
	}

	if !m.GenerateReferenceNumberMock.invocationsDone() && afterGenerateReferenceNumberCounter > 0 {
		m.t.Errorf("Expected %d calls to ReferenceGeneratorMock.GenerateReferenceNumber at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GenerateReferenceNumberMock.expectedInvocations), m.GenerateReferenceNumberMock.expectedInvocationsOrigin, afterGenerateReferenceNumberCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ReferenceGeneratorMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGenerateReferenceNumberInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ReferenceGeneratorMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ReferenceGeneratorMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGenerateReferenceNumberDone()
}
