// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package shipment

//go:generate minimock -i github.com/bazeeko/vektor-shipment/internal/services/shipment.Repository -o repository_mock_test.go -n RepositoryMock -p shipment

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	shipmentrepository "github.com/bazeeko/vektor-shipment/internal/repository/postgresql/shipment"
	"github.com/gojuno/minimock/v3"
	"github.com/google/uuid"
)

// RepositoryMock implements Repository
type RepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcInsertEvent          func(ctx context.Context, params shipmentrepository.InsertEventParams) (err error)
	funcInsertEventOrigin    string
	inspectFuncInsertEvent   func(ctx context.Context, params shipmentrepository.InsertEventParams)
	afterInsertEventCounter  uint64
	beforeInsertEventCounter uint64
	InsertEventMock          mRepositoryMockInsertEvent

	funcInsertShipment          func(ctx context.Context, params shipmentrepository.InsertShipmentParams) (u1 uuid.UUID, err error)
	funcInsertShipmentOrigin    string
	inspectFuncInsertShipment   func(ctx context.Context, params shipmentrepository.InsertShipmentParams)
	afterInsertShipmentCounter  uint64
	beforeInsertShipmentCounter uint64
	InsertShipmentMock          mRepositoryMockInsertShipment

	funcSelectEvents          func(ctx context.Context, shipmentID uuid.UUID) (sa1 []shipmentrepository.SelectEventOutput, err error)
	funcSelectEventsOrigin    string
	inspectFuncSelectEvents   func(ctx context.Context, shipmentID uuid.UUID)
	afterSelectEventsCounter  uint64
	beforeSelectEventsCounter uint64
	SelectEventsMock          mRepositoryMockSelectEvents

	funcSelectLastEvent          func(ctx context.Context, shipmentID uuid.UUID) (s1 shipmentrepository.SelectEventOutput, err error)
	funcSelectLastEventOrigin    string
	inspectFuncSelectLastEvent   func(ctx context.Context, shipmentID uuid.UUID)
	afterSelectLastEventCounter  uint64
	beforeSelectLastEventCounter uint64
	SelectLastEventMock          mRepositoryMockSelectLastEvent

	funcSelectShipment          func(ctx context.Context, shipmentID uuid.UUID) (s1 shipmentrepository.SelectShipmentOutput, err error)
	funcSelectShipmentOrigin    string
	inspectFuncSelectShipment   func(ctx context.Context, shipmentID uuid.UUID)
	afterSelectShipmentCounter  uint64
	beforeSelectShipmentCounter uint64
	SelectShipmentMock          mRepositoryMockSelectShipment
}

// NewRepositoryMock returns a mock for Repository
func NewRepositoryMock(t minimock.Tester) *RepositoryMock {
	m := &RepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.InsertEventMock = mRepositoryMockInsertEvent{mock: m}
	m.InsertEventMock.callArgs = []*RepositoryMockInsertEventParams{}

	m.InsertShipmentMock = mRepositoryMockInsertShipment{mock: m}
	m.InsertShipmentMock.callArgs = []*RepositoryMockInsertShipmentParams{}

	m.SelectEventsMock = mRepositoryMockSelectEvents{mock: m}
	m.SelectEventsMock.callArgs = []*RepositoryMockSelectEventsParams{}

	m.SelectLastEventMock = mRepositoryMockSelectLastEvent{mock: m}
	m.SelectLastEventMock.callArgs = []*RepositoryMockSelectLastEventParams{}

	m.SelectShipmentMock = mRepositoryMockSelectShipment{mock: m}
	m.SelectShipmentMock.callArgs = []*RepositoryMockSelectShipmentParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mRepositoryMockInsertEvent struct {
	optional           bool
	mock               *RepositoryMock
	defaultExpectation *RepositoryMockInsertEventExpectation
	expectations       []*RepositoryMockInsertEventExpectation

	callArgs []*RepositoryMockInsertEventParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RepositoryMockInsertEventExpectation specifies expectation struct of the Repository.InsertEvent
type RepositoryMockInsertEventExpectation struct {
	mock               *RepositoryMock
	params             *RepositoryMockInsertEventParams
	paramPtrs          *RepositoryMockInsertEventParamPtrs
	expectationOrigins RepositoryMockInsertEventExpectationOrigins
	results            *RepositoryMockInsertEventResults
	returnOrigin       string
	Counter            uint64
}

// RepositoryMockInsertEventParams contains parameters of the Repository.InsertEvent
type RepositoryMockInsertEventParams struct {
	ctx    context.Context
	params shipmentrepository.InsertEventParams
}

// RepositoryMockInsertEventParamPtrs contains pointers to parameters of the Repository.InsertEvent
type RepositoryMockInsertEventParamPtrs struct {
	ctx    *context.Context
	params *shipmentrepository.InsertEventParams
}

// RepositoryMockInsertEventResults contains results of the Repository.InsertEvent
type RepositoryMockInsertEventResults struct {
	err error
}

// RepositoryMockInsertEventOrigins contains origins of expectations of the Repository.InsertEvent
type RepositoryMockInsertEventExpectationOrigins struct {
	origin       string
	originCtx    string
	originParams string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmInsertEvent *mRepositoryMockInsertEvent) Optional() *mRepositoryMockInsertEvent {
	mmInsertEvent.optional = true
	return mmInsertEvent
}

// Expect sets up expected params for Repository.InsertEvent
func (mmInsertEvent *mRepositoryMockInsertEvent) Expect(ctx context.Context, params shipmentrepository.InsertEventParams) *mRepositoryMockInsertEvent {
	if mmInsertEvent.mock.funcInsertEvent != nil {
		mmInsertEvent.mock.t.Fatalf("RepositoryMock.InsertEvent mock is already set by Set")
	}

	if mmInsertEvent.defaultExpectation == nil {
		mmInsertEvent.defaultExpectation = &RepositoryMockInsertEventExpectation{}
	}

	if mmInsertEvent.defaultExpectation.paramPtrs != nil {
		mmInsertEvent.mock.t.Fatalf("RepositoryMock.InsertEvent mock is already set by ExpectParams functions")
	}

	mmInsertEvent.defaultExpectation.params = &RepositoryMockInsertEventParams{ctx, params}
	mmInsertEvent.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmInsertEvent.expectations {
		if minimock.Equal(e.params, mmInsertEvent.defaultExpectation.params) {
			mmInsertEvent.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmInsertEvent.defaultExpectation.params)
		}
	}

	return mmInsertEvent
}

// ExpectCtxParam1 sets up expected param ctx for Repository.InsertEvent
func (mmInsertEvent *mRepositoryMockInsertEvent) ExpectCtxParam1(ctx context.Context) *mRepositoryMockInsertEvent {
	if mmInsertEvent.mock.funcInsertEvent != nil {
		mmInsertEvent.mock.t.Fatalf("RepositoryMock.InsertEvent mock is already set by Set")
	}

	if mmInsertEvent.defaultExpectation == nil {
		mmInsertEvent.defaultExpectation = &RepositoryMockInsertEventExpectation{}
	}

	if mmInsertEvent.defaultExpectation.params != nil {
		mmInsertEvent.mock.t.Fatalf("RepositoryMock.InsertEvent mock is already set by Expect")
	}

	if mmInsertEvent.defaultExpectation.paramPtrs == nil {
		mmInsertEvent.defaultExpectation.paramPtrs = &RepositoryMockInsertEventParamPtrs{}
	}
	mmInsertEvent.defaultExpectation.paramPtrs.ctx = &ctx
	mmInsertEvent.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmInsertEvent
}

// ExpectParamsParam2 sets up expected param params for Repository.InsertEvent
func (mmInsertEvent *mRepositoryMockInsertEvent) ExpectParamsParam2(params shipmentrepository.InsertEventParams) *mRepositoryMockInsertEvent {
	if mmInsertEvent.mock.funcInsertEvent != nil {
		mmInsertEvent.mock.t.Fatalf("RepositoryMock.InsertEvent mock is already set by Set")
	}

	if mmInsertEvent.defaultExpectation == nil {
		mmInsertEvent.defaultExpectation = &RepositoryMockInsertEventExpectation{}
	}

	if mmInsertEvent.defaultExpectation.params != nil {
		mmInsertEvent.mock.t.Fatalf("RepositoryMock.InsertEvent mock is already set by Expect")
	}

	if mmInsertEvent.defaultExpectation.paramPtrs == nil {
		mmInsertEvent.defaultExpectation.paramPtrs = &RepositoryMockInsertEventParamPtrs{}
	}
	mmInsertEvent.defaultExpectation.paramPtrs.params = &params
	mmInsertEvent.defaultExpectation.expectationOrigins.originParams = minimock.CallerInfo(1)

	return mmInsertEvent
}

// Inspect accepts an inspector function that has same arguments as the Repository.InsertEvent
func (mmInsertEvent *mRepositoryMockInsertEvent) Inspect(f func(ctx context.Context, params shipmentrepository.InsertEventParams)) *mRepositoryMockInsertEvent {
	if mmInsertEvent.mock.inspectFuncInsertEvent != nil {
		mmInsertEvent.mock.t.Fatalf("Inspect function is already set for RepositoryMock.InsertEvent")
	}

	mmInsertEvent.mock.inspectFuncInsertEvent = f

	return mmInsertEvent
}

// Return sets up results that will be returned by Repository.InsertEvent
func (mmInsertEvent *mRepositoryMockInsertEvent) Return(err error) *RepositoryMock {
	if mmInsertEvent.mock.funcInsertEvent != nil {
		mmInsertEvent.mock.t.Fatalf("RepositoryMock.InsertEvent mock is already set by Set")
	}

	if mmInsertEvent.defaultExpectation == nil {
		mmInsertEvent.defaultExpectation = &RepositoryMockInsertEventExpectation{mock: mmInsertEvent.mock}
	}
	mmInsertEvent.defaultExpectation.results = &RepositoryMockInsertEventResults{err}
	mmInsertEvent.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmInsertEvent.mock
}

// Set uses given function f to mock the Repository.InsertEvent method
func (mmInsertEvent *mRepositoryMockInsertEvent) Set(f func(ctx context.Context, params shipmentrepository.InsertEventParams) (err error)) *RepositoryMock {
	if mmInsertEvent.defaultExpectation != nil {
		mmInsertEvent.mock.t.Fatalf("Default expectation is already set for the Repository.InsertEvent method")
	}

	if len(mmInsertEvent.expectations) > 0 {
		mmInsertEvent.mock.t.Fatalf("Some expectations are already set for the Repository.InsertEvent method")
	}

	mmInsertEvent.mock.funcInsertEvent = f
	mmInsertEvent.mock.funcInsertEventOrigin = minimock.CallerInfo(1)
	return mmInsertEvent.mock
}

// When sets expectation for the Repository.InsertEvent which will trigger the result defined by the following
// Then helper
func (mmInsertEvent *mRepositoryMockInsertEvent) When(ctx context.Context, params shipmentrepository.InsertEventParams) *RepositoryMockInsertEventExpectation {
	if mmInsertEvent.mock.funcInsertEvent != nil {
		mmInsertEvent.mock.t.Fatalf("RepositoryMock.InsertEvent mock is already set by Set")
	}

	expectation := &RepositoryMockInsertEventExpectation{
		mock:               mmInsertEvent.mock,
		params:             &RepositoryMockInsertEventParams{ctx, params},
		expectationOrigins: RepositoryMockInsertEventExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmInsertEvent.expectations = append(mmInsertEvent.expectations, expectation)
	return expectation
}

// Then sets up Repository.InsertEvent return parameters for the expectation previously defined by the When method
func (e *RepositoryMockInsertEventExpectation) Then(err error) *RepositoryMock {
	e.results = &RepositoryMockInsertEventResults{err}
	return e.mock
}

// Times sets number of times Repository.InsertEvent should be invoked
func (mmInsertEvent *mRepositoryMockInsertEvent) Times(n uint64) *mRepositoryMockInsertEvent {
	if n == 0 {
		mmInsertEvent.mock.t.Fatalf("Times of RepositoryMock.InsertEvent mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmInsertEvent.expectedInvocations, n)
	mmInsertEvent.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmInsertEvent
}

func (mmInsertEvent *mRepositoryMockInsertEvent) invocationsDone() bool {
	if len(mmInsertEvent.expectations) == 0 && mmInsertEvent.defaultExpectation == nil && mmInsertEvent.mock.funcInsertEvent == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmInsertEvent.mock.afterInsertEventCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmInsertEvent.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// InsertEvent implements Repository
func (mmInsertEvent *RepositoryMock) InsertEvent(ctx context.Context, params shipmentrepository.InsertEventParams) (err error) {
	mm_atomic.AddUint64(&mmInsertEvent.beforeInsertEventCounter, 1)
	defer mm_atomic.AddUint64(&mmInsertEvent.afterInsertEventCounter, 1)

	mmInsertEvent.t.Helper()

	if mmInsertEvent.inspectFuncInsertEvent != nil {
		mmInsertEvent.inspectFuncInsertEvent(ctx, params)
	}

	mm_params := RepositoryMockInsertEventParams{ctx, params}

	// Record call args
	mmInsertEvent.InsertEventMock.mutex.Lock()
	mmInsertEvent.InsertEventMock.callArgs = append(mmInsertEvent.InsertEventMock.callArgs, &mm_params)
	mmInsertEvent.InsertEventMock.mutex.Unlock()

	for _, e := range mmInsertEvent.InsertEventMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmInsertEvent.InsertEventMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmInsertEvent.InsertEventMock.defaultExpectation.Counter, 1)
		mm_want := mmInsertEvent.InsertEventMock.defaultExpectation.params
		mm_want_ptrs := mmInsertEvent.InsertEventMock.defaultExpectation.paramPtrs

		mm_got := RepositoryMockInsertEventParams{ctx, params}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmInsertEvent.t.Errorf("RepositoryMock.InsertEvent got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInsertEvent.InsertEventMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.params != nil && !minimock.Equal(*mm_want_ptrs.params, mm_got.params) {
				mmInsertEvent.t.Errorf("RepositoryMock.InsertEvent got unexpected parameter params, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInsertEvent.InsertEventMock.defaultExpectation.expectationOrigins.originParams, *mm_want_ptrs.params, mm_got.params, minimock.Diff(*mm_want_ptrs.params, mm_got.params))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmInsertEvent.t.Errorf("RepositoryMock.InsertEvent got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmInsertEvent.InsertEventMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmInsertEvent.InsertEventMock.defaultExpectation.results
		if mm_results == nil {
			mmInsertEvent.t.Fatal("No results are set for the RepositoryMock.InsertEvent")
		}
		return (*mm_results).err
	}
	if mmInsertEvent.funcInsertEvent != nil {
		return mmInsertEvent.funcInsertEvent(ctx, params)
	}
	mmInsertEvent.t.Fatalf("Unexpected call to RepositoryMock.InsertEvent. %v %v", ctx, params)
	return
}

// InsertEventAfterCounter returns a count of finished RepositoryMock.InsertEvent invocations
func (mmInsertEvent *RepositoryMock) InsertEventAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInsertEvent.afterInsertEventCounter)
}

// InsertEventBeforeCounter returns a count of RepositoryMock.InsertEvent invocations
func (mmInsertEvent *RepositoryMock) InsertEventBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInsertEvent.beforeInsertEventCounter)
}

// Calls returns a list of arguments used in each call to RepositoryMock.InsertEvent.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmInsertEvent *mRepositoryMockInsertEvent) Calls() []*RepositoryMockInsertEventParams {
	mmInsertEvent.mutex.RLock()

	argCopy := make([]*RepositoryMockInsertEventParams, len(mmInsertEvent.callArgs))
	copy(argCopy, mmInsertEvent.callArgs)

	mmInsertEvent.mutex.RUnlock()

	return argCopy
}

// MinimockInsertEventDone returns true if the count of the InsertEvent invocations corresponds
// the number of defined expectations
func (m *RepositoryMock) MinimockInsertEventDone() bool {
	if m.InsertEventMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.InsertEventMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.InsertEventMock.invocationsDone()
}

// MinimockInsertEventInspect logs each unmet expectation
func (m *RepositoryMock) MinimockInsertEventInspect() {
	for _, e := range m.InsertEventMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepositoryMock.InsertEvent at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterInsertEventCounter := mm_atomic.LoadUint64(&m.afterInsertEventCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.InsertEventMock.defaultExpectation != nil && afterInsertEventCounter < 1 {
		if m.InsertEventMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RepositoryMock.InsertEvent at\n%s", m.InsertEventMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RepositoryMock.InsertEvent at\n%s with params: %#v", m.InsertEventMock.defaultExpectation.expectationOrigins.origin, *m.InsertEventMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcInsertEvent != nil && afterInsertEventCounter < 1 {
		m.t.Errorf("Expected call to RepositoryMock.InsertEvent at\n%s", m.funcInsertEventOrigin)
	}

	if !m.InsertEventMock.invocationsDone() && afterInsertEventCounter > 0 {
		m.t.Errorf("Expected %d calls to RepositoryMock.InsertEvent at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.InsertEventMock.expectedInvocations), m.InsertEventMock.expectedInvocationsOrigin, afterInsertEventCounter)
	}
}

type mRepositoryMockInsertShipment struct {
	optional           bool
	mock               *RepositoryMock
	defaultExpectation *RepositoryMockInsertShipmentExpectation
	expectations       []*RepositoryMockInsertShipmentExpectation

	callArgs []*RepositoryMockInsertShipmentParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RepositoryMockInsertShipmentExpectation specifies expectation struct of the Repository.InsertShipment
type RepositoryMockInsertShipmentExpectation struct {
	mock               *RepositoryMock
	params             *RepositoryMockInsertShipmentParams
	paramPtrs          *RepositoryMockInsertShipmentParamPtrs
	expectationOrigins RepositoryMockInsertShipmentExpectationOrigins
	results            *RepositoryMockInsertShipmentResults
	returnOrigin       string
	Counter            uint64
}

// RepositoryMockInsertShipmentParams contains parameters of the Repository.InsertShipment
type RepositoryMockInsertShipmentParams struct {
	ctx    context.Context
	params shipmentrepository.InsertShipmentParams
}

// RepositoryMockInsertShipmentParamPtrs contains pointers to parameters of the Repository.InsertShipment
type RepositoryMockInsertShipmentParamPtrs struct {
	ctx    *context.Context
	params *shipmentrepository.InsertShipmentParams
}

// RepositoryMockInsertShipmentResults contains results of the Repository.InsertShipment
type RepositoryMockInsertShipmentResults struct {
	u1  uuid.UUID
	err error
}

// RepositoryMockInsertShipmentOrigins contains origins of expectations of the Repository.InsertShipment
type RepositoryMockInsertShipmentExpectationOrigins struct {
	origin       string
	originCtx    string
	originParams string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmInsertShipment *mRepositoryMockInsertShipment) Optional() *mRepositoryMockInsertShipment {
	mmInsertShipment.optional = true
	return mmInsertShipment
}

// Expect sets up expected params for Repository.InsertShipment
func (mmInsertShipment *mRepositoryMockInsertShipment) Expect(ctx context.Context, params shipmentrepository.InsertShipmentParams) *mRepositoryMockInsertShipment {
	if mmInsertShipment.mock.funcInsertShipment != nil {
		mmInsertShipment.mock.t.Fatalf("RepositoryMock.InsertShipment mock is already set by Set")
	}

	if mmInsertShipment.defaultExpectation == nil {
		mmInsertShipment.defaultExpectation = &RepositoryMockInsertShipmentExpectation{}
	}

	if mmInsertShipment.defaultExpectation.paramPtrs != nil {
		mmInsertShipment.mock.t.Fatalf("RepositoryMock.InsertShipment mock is already set by ExpectParams functions")
	}

	mmInsertShipment.defaultExpectation.params = &RepositoryMockInsertShipmentParams{ctx, params}
	mmInsertShipment.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmInsertShipment.expectations {
		if minimock.Equal(e.params, mmInsertShipment.defaultExpectation.params) {
			mmInsertShipment.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmInsertShipment.defaultExpectation.params)
		}
	}

	return mmInsertShipment
}

// ExpectCtxParam1 sets up expected param ctx for Repository.InsertShipment
func (mmInsertShipment *mRepositoryMockInsertShipment) ExpectCtxParam1(ctx context.Context) *mRepositoryMockInsertShipment {
	if mmInsertShipment.mock.funcInsertShipment != nil {
		mmInsertShipment.mock.t.Fatalf("RepositoryMock.InsertShipment mock is already set by Set")
	}

	if mmInsertShipment.defaultExpectation == nil {
		mmInsertShipment.defaultExpectation = &RepositoryMockInsertShipmentExpectation{}
	}

	if mmInsertShipment.defaultExpectation.params != nil {
		mmInsertShipment.mock.t.Fatalf("RepositoryMock.InsertShipment mock is already set by Expect")
	}

	if mmInsertShipment.defaultExpectation.paramPtrs == nil {
		mmInsertShipment.defaultExpectation.paramPtrs = &RepositoryMockInsertShipmentParamPtrs{}
	}
	mmInsertShipment.defaultExpectation.paramPtrs.ctx = &ctx
	mmInsertShipment.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmInsertShipment
}

// ExpectParamsParam2 sets up expected param params for Repository.InsertShipment
func (mmInsertShipment *mRepositoryMockInsertShipment) ExpectParamsParam2(params shipmentrepository.InsertShipmentParams) *mRepositoryMockInsertShipment {
	if mmInsertShipment.mock.funcInsertShipment != nil {
		mmInsertShipment.mock.t.Fatalf("RepositoryMock.InsertShipment mock is already set by Set")
	}

	if mmInsertShipment.defaultExpectation == nil {
		mmInsertShipment.defaultExpectation = &RepositoryMockInsertShipmentExpectation{}
	}

	if mmInsertShipment.defaultExpectation.params != nil {
		mmInsertShipment.mock.t.Fatalf("RepositoryMock.InsertShipment mock is already set by Expect")
	}

	if mmInsertShipment.defaultExpectation.paramPtrs == nil {
		mmInsertShipment.defaultExpectation.paramPtrs = &RepositoryMockInsertShipmentParamPtrs{}
	}
	mmInsertShipment.defaultExpectation.paramPtrs.params = &params
	mmInsertShipment.defaultExpectation.expectationOrigins.originParams = minimock.CallerInfo(1)

	return mmInsertShipment
}

// Inspect accepts an inspector function that has same arguments as the Repository.InsertShipment
func (mmInsertShipment *mRepositoryMockInsertShipment) Inspect(f func(ctx context.Context, params shipmentrepository.InsertShipmentParams)) *mRepositoryMockInsertShipment {
	if mmInsertShipment.mock.inspectFuncInsertShipment != nil {
		mmInsertShipment.mock.t.Fatalf("Inspect function is already set for RepositoryMock.InsertShipment")
	}

	mmInsertShipment.mock.inspectFuncInsertShipment = f

	return mmInsertShipment
}

// Return sets up results that will be returned by Repository.InsertShipment
func (mmInsertShipment *mRepositoryMockInsertShipment) Return(u1 uuid.UUID, err error) *RepositoryMock {
	if mmInsertShipment.mock.funcInsertShipment != nil {
		mmInsertShipment.mock.t.Fatalf("RepositoryMock.InsertShipment mock is already set by Set")
	}

	if mmInsertShipment.defaultExpectation == nil {
		mmInsertShipment.defaultExpectation = &RepositoryMockInsertShipmentExpectation{mock: mmInsertShipment.mock}
	}
	mmInsertShipment.defaultExpectation.results = &RepositoryMockInsertShipmentResults{u1, err}
	mmInsertShipment.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmInsertShipment.mock
}

// Set uses given function f to mock the Repository.InsertShipment method
func (mmInsertShipment *mRepositoryMockInsertShipment) Set(f func(ctx context.Context, params shipmentrepository.InsertShipmentParams) (u1 uuid.UUID, err error)) *RepositoryMock {
	if mmInsertShipment.defaultExpectation != nil {
		mmInsertShipment.mock.t.Fatalf("Default expectation is already set for the Repository.InsertShipment method")
	}

	if len(mmInsertShipment.expectations) > 0 {
		mmInsertShipment.mock.t.Fatalf("Some expectations are already set for the Repository.InsertShipment method")
	}

	mmInsertShipment.mock.funcInsertShipment = f
	mmInsertShipment.mock.funcInsertShipmentOrigin = minimock.CallerInfo(1)
	return mmInsertShipment.mock
}

// When sets expectation for the Repository.InsertShipment which will trigger the result defined by the following
// Then helper
func (mmInsertShipment *mRepositoryMockInsertShipment) When(ctx context.Context, params shipmentrepository.InsertShipmentParams) *RepositoryMockInsertShipmentExpectation {
	if mmInsertShipment.mock.funcInsertShipment != nil {
		mmInsertShipment.mock.t.Fatalf("RepositoryMock.InsertShipment mock is already set by Set")
	}

	expectation := &RepositoryMockInsertShipmentExpectation{
		mock:               mmInsertShipment.mock,
		params:             &RepositoryMockInsertShipmentParams{ctx, params},
		expectationOrigins: RepositoryMockInsertShipmentExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmInsertShipment.expectations = append(mmInsertShipment.expectations, expectation)
	return expectation
}

// Then sets up Repository.InsertShipment return parameters for the expectation previously defined by the When method
func (e *RepositoryMockInsertShipmentExpectation) Then(u1 uuid.UUID, err error) *RepositoryMock {
	e.results = &RepositoryMockInsertShipmentResults{u1, err}
	return e.mock
}

// Times sets number of times Repository.InsertShipment should be invoked
func (mmInsertShipment *mRepositoryMockInsertShipment) Times(n uint64) *mRepositoryMockInsertShipment {
	if n == 0 {
		mmInsertShipment.mock.t.Fatalf("Times of RepositoryMock.InsertShipment mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmInsertShipment.expectedInvocations, n)
	mmInsertShipment.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmInsertShipment
}

func (mmInsertShipment *mRepositoryMockInsertShipment) invocationsDone() bool {
	if len(mmInsertShipment.expectations) == 0 && mmInsertShipment.defaultExpectation == nil && mmInsertShipment.mock.funcInsertShipment == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmInsertShipment.mock.afterInsertShipmentCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmInsertShipment.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// InsertShipment implements Repository
func (mmInsertShipment *RepositoryMock) InsertShipment(ctx context.Context, params shipmentrepository.InsertShipmentParams) (u1 uuid.UUID, err error) {
	mm_atomic.AddUint64(&mmInsertShipment.beforeInsertShipmentCounter, 1)
	defer mm_atomic.AddUint64(&mmInsertShipment.afterInsertShipmentCounter, 1)

	mmInsertShipment.t.Helper()

	if mmInsertShipment.inspectFuncInsertShipment != nil {
		mmInsertShipment.inspectFuncInsertShipment(ctx, params)
	}

	mm_params := RepositoryMockInsertShipmentParams{ctx, params}

	// Record call args
	mmInsertShipment.InsertShipmentMock.mutex.Lock()
	mmInsertShipment.InsertShipmentMock.callArgs = append(mmInsertShipment.InsertShipmentMock.callArgs, &mm_params)
	mmInsertShipment.InsertShipmentMock.mutex.Unlock()

	for _, e := range mmInsertShipment.InsertShipmentMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.u1, e.results.err
		}
	}

	if mmInsertShipment.InsertShipmentMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmInsertShipment.InsertShipmentMock.defaultExpectation.Counter, 1)
		mm_want := mmInsertShipment.InsertShipmentMock.defaultExpectation.params
		mm_want_ptrs := mmInsertShipment.InsertShipmentMock.defaultExpectation.paramPtrs

		mm_got := RepositoryMockInsertShipmentParams{ctx, params}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmInsertShipment.t.Errorf("RepositoryMock.InsertShipment got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInsertShipment.InsertShipmentMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.params != nil && !minimock.Equal(*mm_want_ptrs.params, mm_got.params) {
				mmInsertShipment.t.Errorf("RepositoryMock.InsertShipment got unexpected parameter params, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInsertShipment.InsertShipmentMock.defaultExpectation.expectationOrigins.originParams, *mm_want_ptrs.params, mm_got.params, minimock.Diff(*mm_want_ptrs.params, mm_got.params))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmInsertShipment.t.Errorf("RepositoryMock.InsertShipment got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmInsertShipment.InsertShipmentMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmInsertShipment.InsertShipmentMock.defaultExpectation.results
		if mm_results == nil {
			mmInsertShipment.t.Fatal("No results are set for the RepositoryMock.InsertShipment")
		}
		return (*mm_results).u1, (*mm_results).err
	}
	if mmInsertShipment.funcInsertShipment != nil {
		return mmInsertShipment.funcInsertShipment(ctx, params)
	}
	mmInsertShipment.t.Fatalf("Unexpected call to RepositoryMock.InsertShipment. %v %v", ctx, params)
	return
}

// InsertShipmentAfterCounter returns a count of finished RepositoryMock.InsertShipment invocations
func (mmInsertShipment *RepositoryMock) InsertShipmentAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInsertShipment.afterInsertShipmentCounter)
}

// InsertShipmentBeforeCounter returns a count of RepositoryMock.InsertShipment invocations
func (mmInsertShipment *RepositoryMock) InsertShipmentBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInsertShipment.beforeInsertShipmentCounter)
}

// Calls returns a list of arguments used in each call to RepositoryMock.InsertShipment.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmInsertShipment *mRepositoryMockInsertShipment) Calls() []*RepositoryMockInsertShipmentParams {
	mmInsertShipment.mutex.RLock()

	argCopy := make([]*RepositoryMockInsertShipmentParams, len(mmInsertShipment.callArgs))
	copy(argCopy, mmInsertShipment.callArgs)

	mmInsertShipment.mutex.RUnlock()

	return argCopy
}

// MinimockInsertShipmentDone returns true if the count of the InsertShipment invocations corresponds
// the number of defined expectations
func (m *RepositoryMock) MinimockInsertShipmentDone() bool {
	if m.InsertShipmentMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.InsertShipmentMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.InsertShipmentMock.invocationsDone()
}

// MinimockInsertShipmentInspect logs each unmet expectation
func (m *RepositoryMock) MinimockInsertShipmentInspect() {
	for _, e := range m.InsertShipmentMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepositoryMock.InsertShipment at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterInsertShipmentCounter := mm_atomic.LoadUint64(&m.afterInsertShipmentCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.InsertShipmentMock.defaultExpectation != nil && afterInsertShipmentCounter < 1 {
		if m.InsertShipmentMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RepositoryMock.InsertShipment at\n%s", m.InsertShipmentMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RepositoryMock.InsertShipment at\n%s with params: %#v", m.InsertShipmentMock.defaultExpectation.expectationOrigins.origin, *m.InsertShipmentMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcInsertShipment != nil && afterInsertShipmentCounter < 1 {
		m.t.Errorf("Expected call to RepositoryMock.InsertShipment at\n%s", m.funcInsertShipmentOrigin)
	}

	if !m.InsertShipmentMock.invocationsDone() && afterInsertShipmentCounter > 0 {
		m.t.Errorf("Expected %d calls to RepositoryMock.InsertShipment at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.InsertShipmentMock.expectedInvocations), m.InsertShipmentMock.expectedInvocationsOrigin, afterInsertShipmentCounter)
	}
}

type mRepositoryMockSelectEvents struct {
	optional           bool
	mock               *RepositoryMock
	defaultExpectation *RepositoryMockSelectEventsExpectation
	expectations       []*RepositoryMockSelectEventsExpectation

	callArgs []*RepositoryMockSelectEventsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RepositoryMockSelectEventsExpectation specifies expectation struct of the Repository.SelectEvents
type RepositoryMockSelectEventsExpectation struct {
	mock               *RepositoryMock
	params             *RepositoryMockSelectEventsParams
	paramPtrs          *RepositoryMockSelectEventsParamPtrs
	expectationOrigins RepositoryMockSelectEventsExpectationOrigins
	results            *RepositoryMockSelectEventsResults
	returnOrigin       string
	Counter            uint64
}

// RepositoryMockSelectEventsParams contains parameters of the Repository.SelectEvents
type RepositoryMockSelectEventsParams struct {
	ctx        context.Context
	shipmentID uuid.UUID
}

// RepositoryMockSelectEventsParamPtrs contains pointers to parameters of the Repository.SelectEvents
type RepositoryMockSelectEventsParamPtrs struct {
	ctx        *context.Context
	shipmentID *uuid.UUID
}

// RepositoryMockSelectEventsResults contains results of the Repository.SelectEvents
type RepositoryMockSelectEventsResults struct {
	sa1 []shipmentrepository.SelectEventOutput
	err error
}

// RepositoryMockSelectEventsOrigins contains origins of expectations of the Repository.SelectEvents
type RepositoryMockSelectEventsExpectationOrigins struct {
	origin           string
	originCtx        string
	originShipmentID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSelectEvents *mRepositoryMockSelectEvents) Optional() *mRepositoryMockSelectEvents {
	mmSelectEvents.optional = true
	return mmSelectEvents
}

// Expect sets up expected params for Repository.SelectEvents
func (mmSelectEvents *mRepositoryMockSelectEvents) Expect(ctx context.Context, shipmentID uuid.UUID) *mRepositoryMockSelectEvents {
	if mmSelectEvents.mock.funcSelectEvents != nil {
		mmSelectEvents.mock.t.Fatalf("RepositoryMock.SelectEvents mock is already set by Set")
	}

	if mmSelectEvents.defaultExpectation == nil {
		mmSelectEvents.defaultExpectation = &RepositoryMockSelectEventsExpectation{}
	}

	if mmSelectEvents.defaultExpectation.paramPtrs != nil {
		mmSelectEvents.mock.t.Fatalf("RepositoryMock.SelectEvents mock is already set by ExpectParams functions")
	}

	mmSelectEvents.defaultExpectation.params = &RepositoryMockSelectEventsParams{ctx, shipmentID}
	mmSelectEvents.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSelectEvents.expectations {
		if minimock.Equal(e.params, mmSelectEvents.defaultExpectation.params) {
			mmSelectEvents.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSelectEvents.defaultExpectation.params)
		}
	}

	return mmSelectEvents
}

// ExpectCtxParam1 sets up expected param ctx for Repository.SelectEvents
func (mmSelectEvents *mRepositoryMockSelectEvents) ExpectCtxParam1(ctx context.Context) *mRepositoryMockSelectEvents {
	if mmSelectEvents.mock.funcSelectEvents != nil {
		mmSelectEvents.mock.t.Fatalf("RepositoryMock.SelectEvents mock is already set by Set")
	}

	if mmSelectEvents.defaultExpectation == nil {
		mmSelectEvents.defaultExpectation = &RepositoryMockSelectEventsExpectation{}
	}

	if mmSelectEvents.defaultExpectation.params != nil {
		mmSelectEvents.mock.t.Fatalf("RepositoryMock.SelectEvents mock is already set by Expect")
	}

	if mmSelectEvents.defaultExpectation.paramPtrs == nil {
		mmSelectEvents.defaultExpectation.paramPtrs = &RepositoryMockSelectEventsParamPtrs{}
	}
	mmSelectEvents.defaultExpectation.paramPtrs.ctx = &ctx
	mmSelectEvents.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSelectEvents
}

// ExpectShipmentIDParam2 sets up expected param shipmentID for Repository.SelectEvents
func (mmSelectEvents *mRepositoryMockSelectEvents) ExpectShipmentIDParam2(shipmentID uuid.UUID) *mRepositoryMockSelectEvents {
	if mmSelectEvents.mock.funcSelectEvents != nil {
		mmSelectEvents.mock.t.Fatalf("RepositoryMock.SelectEvents mock is already set by Set")
	}

	if mmSelectEvents.defaultExpectation == nil {
		mmSelectEvents.defaultExpectation = &RepositoryMockSelectEventsExpectation{}
	}

	if mmSelectEvents.defaultExpectation.params != nil {
		mmSelectEvents.mock.t.Fatalf("RepositoryMock.SelectEvents mock is already set by Expect")
	}

	if mmSelectEvents.defaultExpectation.paramPtrs == nil {
		mmSelectEvents.defaultExpectation.paramPtrs = &RepositoryMockSelectEventsParamPtrs{}
	}
	mmSelectEvents.defaultExpectation.paramPtrs.shipmentID = &shipmentID
	mmSelectEvents.defaultExpectation.expectationOrigins.originShipmentID = minimock.CallerInfo(1)

	return mmSelectEvents
}

// Inspect accepts an inspector function that has same arguments as the Repository.SelectEvents
func (mmSelectEvents *mRepositoryMockSelectEvents) Inspect(f func(ctx context.Context, shipmentID uuid.UUID)) *mRepositoryMockSelectEvents {
	if mmSelectEvents.mock.inspectFuncSelectEvents != nil {
		mmSelectEvents.mock.t.Fatalf("Inspect function is already set for RepositoryMock.SelectEvents")
	}

	mmSelectEvents.mock.inspectFuncSelectEvents = f

	return mmSelectEvents
}

// Return sets up results that will be returned by Repository.SelectEvents
func (mmSelectEvents *mRepositoryMockSelectEvents) Return(sa1 []shipmentrepository.SelectEventOutput, err error) *RepositoryMock {
	if mmSelectEvents.mock.funcSelectEvents != nil {
		mmSelectEvents.mock.t.Fatalf("RepositoryMock.SelectEvents mock is already set by Set")
	}

	if mmSelectEvents.defaultExpectation == nil {
		mmSelectEvents.defaultExpectation = &RepositoryMockSelectEventsExpectation{mock: mmSelectEvents.mock}
	}
	mmSelectEvents.defaultExpectation.results = &RepositoryMockSelectEventsResults{sa1, err}
	mmSelectEvents.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSelectEvents.mock
}

// Set uses given function f to mock the Repository.SelectEvents method
func (mmSelectEvents *mRepositoryMockSelectEvents) Set(f func(ctx context.Context, shipmentID uuid.UUID) (sa1 []shipmentrepository.SelectEventOutput, err error)) *RepositoryMock {
	if mmSelectEvents.defaultExpectation != nil {
		mmSelectEvents.mock.t.Fatalf("Default expectation is already set for the Repository.SelectEvents method")
	}

	if len(mmSelectEvents.expectations) > 0 {
		mmSelectEvents.mock.t.Fatalf("Some expectations are already set for the Repository.SelectEvents method")
	}

	mmSelectEvents.mock.funcSelectEvents = f
	mmSelectEvents.mock.funcSelectEventsOrigin = minimock.CallerInfo(1)
	return mmSelectEvents.mock
}

// When sets expectation for the Repository.SelectEvents which will trigger the result defined by the following
// Then helper
func (mmSelectEvents *mRepositoryMockSelectEvents) When(ctx context.Context, shipmentID uuid.UUID) *RepositoryMockSelectEventsExpectation {
	if mmSelectEvents.mock.funcSelectEvents != nil {
		mmSelectEvents.mock.t.Fatalf("RepositoryMock.SelectEvents mock is already set by Set")
	}

	expectation := &RepositoryMockSelectEventsExpectation{
		mock:               mmSelectEvents.mock,
		params:             &RepositoryMockSelectEventsParams{ctx, shipmentID},
		expectationOrigins: RepositoryMockSelectEventsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSelectEvents.expectations = append(mmSelectEvents.expectations, expectation)
	return expectation
}

// Then sets up Repository.SelectEvents return parameters for the expectation previously defined by the When method
func (e *RepositoryMockSelectEventsExpectation) Then(sa1 []shipmentrepository.SelectEventOutput, err error) *RepositoryMock {
	e.results = &RepositoryMockSelectEventsResults{sa1, err}
	return e.mock
}

// Times sets number of times Repository.SelectEvents should be invoked
func (mmSelectEvents *mRepositoryMockSelectEvents) Times(n uint64) *mRepositoryMockSelectEvents {
	if n == 0 {
		mmSelectEvents.mock.t.Fatalf("Times of RepositoryMock.SelectEvents mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSelectEvents.expectedInvocations, n)
	mmSelectEvents.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSelectEvents
}

func (mmSelectEvents *mRepositoryMockSelectEvents) invocationsDone() bool {
	if len(mmSelectEvents.expectations) == 0 && mmSelectEvents.defaultExpectation == nil && mmSelectEvents.mock.funcSelectEvents == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSelectEvents.mock.afterSelectEventsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSelectEvents.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SelectEvents implements Repository
func (mmSelectEvents *RepositoryMock) SelectEvents(ctx context.Context, shipmentID uuid.UUID) (sa1 []shipmentrepository.SelectEventOutput, err error) {
	mm_atomic.AddUint64(&mmSelectEvents.beforeSelectEventsCounter, 1)
	defer mm_atomic.AddUint64(&mmSelectEvents.afterSelectEventsCounter, 1)

	mmSelectEvents.t.Helper()

	if mmSelectEvents.inspectFuncSelectEvents != nil {
		mmSelectEvents.inspectFuncSelectEvents(ctx, shipmentID)
	}

	mm_params := RepositoryMockSelectEventsParams{ctx, shipmentID}

	// Record call args
	mmSelectEvents.SelectEventsMock.mutex.Lock()
	mmSelectEvents.SelectEventsMock.callArgs = append(mmSelectEvents.SelectEventsMock.callArgs, &mm_params)
	mmSelectEvents.SelectEventsMock.mutex.Unlock()

	for _, e := range mmSelectEvents.SelectEventsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sa1, e.results.err
		}
	}

	if mmSelectEvents.SelectEventsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSelectEvents.SelectEventsMock.defaultExpectation.Counter, 1)
		mm_want := mmSelectEvents.SelectEventsMock.defaultExpectation.params
		mm_want_ptrs := mmSelectEvents.SelectEventsMock.defaultExpectation.paramPtrs

		mm_got := RepositoryMockSelectEventsParams{ctx, shipmentID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSelectEvents.t.Errorf("RepositoryMock.SelectEvents got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSelectEvents.SelectEventsMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.shipmentID != nil && !minimock.Equal(*mm_want_ptrs.shipmentID, mm_got.shipmentID) {
				mmSelectEvents.t.Errorf("RepositoryMock.SelectEvents got unexpected parameter shipmentID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSelectEvents.SelectEventsMock.defaultExpectation.expectationOrigins.originShipmentID, *mm_want_ptrs.shipmentID, mm_got.shipmentID, minimock.Diff(*mm_want_ptrs.shipmentID, mm_got.shipmentID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSelectEvents.t.Errorf("RepositoryMock.SelectEvents got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSelectEvents.SelectEventsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSelectEvents.SelectEventsMock.defaultExpectation.results
		if mm_results == nil {
			mmSelectEvents.t.Fatal("No results are set for the RepositoryMock.SelectEvents")
		}
		return (*mm_results).sa1, (*mm_results).err
	}
	if mmSelectEvents.funcSelectEvents != nil {
		return mmSelectEvents.funcSelectEvents(ctx, shipmentID)
	}
	mmSelectEvents.t.Fatalf("Unexpected call to RepositoryMock.SelectEvents. %v %v", ctx, shipmentID)
	return
}

// SelectEventsAfterCounter returns a count of finished RepositoryMock.SelectEvents invocations
func (mmSelectEvents *RepositoryMock) SelectEventsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSelectEvents.afterSelectEventsCounter)
}

// SelectEventsBeforeCounter returns a count of RepositoryMock.SelectEvents invocations
func (mmSelectEvents *RepositoryMock) SelectEventsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSelectEvents.beforeSelectEventsCounter)
}

// Calls returns a list of arguments used in each call to RepositoryMock.SelectEvents.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSelectEvents *mRepositoryMockSelectEvents) Calls() []*RepositoryMockSelectEventsParams {
	mmSelectEvents.mutex.RLock()

	argCopy := make([]*RepositoryMockSelectEventsParams, len(mmSelectEvents.callArgs))
	copy(argCopy, mmSelectEvents.callArgs)

	mmSelectEvents.mutex.RUnlock()

	return argCopy
}

// MinimockSelectEventsDone returns true if the count of the SelectEvents invocations corresponds
// the number of defined expectations
func (m *RepositoryMock) MinimockSelectEventsDone() bool {
	if m.SelectEventsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SelectEventsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SelectEventsMock.invocationsDone()
}

// MinimockSelectEventsInspect logs each unmet expectation
func (m *RepositoryMock) MinimockSelectEventsInspect() {
	for _, e := range m.SelectEventsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepositoryMock.SelectEvents at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSelectEventsCounter := mm_atomic.LoadUint64(&m.afterSelectEventsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SelectEventsMock.defaultExpectation != nil && afterSelectEventsCounter < 1 {
		if m.SelectEventsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RepositoryMock.SelectEvents at\n%s", m.SelectEventsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RepositoryMock.SelectEvents at\n%s with params: %#v", m.SelectEventsMock.defaultExpectation.expectationOrigins.origin, *m.SelectEventsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSelectEvents != nil && afterSelectEventsCounter < 1 {
		m.t.Errorf("Expected call to RepositoryMock.SelectEvents at\n%s", m.funcSelectEventsOrigin)
	}

	if !m.SelectEventsMock.invocationsDone() && afterSelectEventsCounter > 0 {
		m.t.Errorf("Expected %d calls to RepositoryMock.SelectEvents at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SelectEventsMock.expectedInvocations), m.SelectEventsMock.expectedInvocationsOrigin, afterSelectEventsCounter)
	}
}

type mRepositoryMockSelectLastEvent struct {
	optional           bool
	mock               *RepositoryMock
	defaultExpectation *RepositoryMockSelectLastEventExpectation
	expectations       []*RepositoryMockSelectLastEventExpectation

	callArgs []*RepositoryMockSelectLastEventParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RepositoryMockSelectLastEventExpectation specifies expectation struct of the Repository.SelectLastEvent
type RepositoryMockSelectLastEventExpectation struct {
	mock               *RepositoryMock
	params             *RepositoryMockSelectLastEventParams
	paramPtrs          *RepositoryMockSelectLastEventParamPtrs
	expectationOrigins RepositoryMockSelectLastEventExpectationOrigins
	results            *RepositoryMockSelectLastEventResults
	returnOrigin       string
	Counter            uint64
}

// RepositoryMockSelectLastEventParams contains parameters of the Repository.SelectLastEvent
type RepositoryMockSelectLastEventParams struct {
	ctx        context.Context
	shipmentID uuid.UUID
}

// RepositoryMockSelectLastEventParamPtrs contains pointers to parameters of the Repository.SelectLastEvent
type RepositoryMockSelectLastEventParamPtrs struct {
	ctx        *context.Context
	shipmentID *uuid.UUID
}

// RepositoryMockSelectLastEventResults contains results of the Repository.SelectLastEvent
type RepositoryMockSelectLastEventResults struct {
	s1  shipmentrepository.SelectEventOutput
	err error
}

// RepositoryMockSelectLastEventOrigins contains origins of expectations of the Repository.SelectLastEvent
type RepositoryMockSelectLastEventExpectationOrigins struct {
	origin           string
	originCtx        string
	originShipmentID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSelectLastEvent *mRepositoryMockSelectLastEvent) Optional() *mRepositoryMockSelectLastEvent {
	mmSelectLastEvent.optional = true
	return mmSelectLastEvent
}

// Expect sets up expected params for Repository.SelectLastEvent
func (mmSelectLastEvent *mRepositoryMockSelectLastEvent) Expect(ctx context.Context, shipmentID uuid.UUID) *mRepositoryMockSelectLastEvent {
	if mmSelectLastEvent.mock.funcSelectLastEvent != nil {
		mmSelectLastEvent.mock.t.Fatalf("RepositoryMock.SelectLastEvent mock is already set by Set")
	}

	if mmSelectLastEvent.defaultExpectation == nil {
		mmSelectLastEvent.defaultExpectation = &RepositoryMockSelectLastEventExpectation{}
	}

	if mmSelectLastEvent.defaultExpectation.paramPtrs != nil {
		mmSelectLastEvent.mock.t.Fatalf("RepositoryMock.SelectLastEvent mock is already set by ExpectParams functions")
	}

	mmSelectLastEvent.defaultExpectation.params = &RepositoryMockSelectLastEventParams{ctx, shipmentID}
	mmSelectLastEvent.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSelectLastEvent.expectations {
		if minimock.Equal(e.params, mmSelectLastEvent.defaultExpectation.params) {
			mmSelectLastEvent.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSelectLastEvent.defaultExpectation.params)
		}
	}

	return mmSelectLastEvent
}

// ExpectCtxParam1 sets up expected param ctx for Repository.SelectLastEvent
func (mmSelectLastEvent *mRepositoryMockSelectLastEvent) ExpectCtxParam1(ctx context.Context) *mRepositoryMockSelectLastEvent {
	if mmSelectLastEvent.mock.funcSelectLastEvent != nil {
		mmSelectLastEvent.mock.t.Fatalf("RepositoryMock.SelectLastEvent mock is already set by Set")
	}

	if mmSelectLastEvent.defaultExpectation == nil {
		mmSelectLastEvent.defaultExpectation = &RepositoryMockSelectLastEventExpectation{}
	}

	if mmSelectLastEvent.defaultExpectation.params != nil {
		mmSelectLastEvent.mock.t.Fatalf("RepositoryMock.SelectLastEvent mock is already set by Expect")
	}

	if mmSelectLastEvent.defaultExpectation.paramPtrs == nil {
		mmSelectLastEvent.defaultExpectation.paramPtrs = &RepositoryMockSelectLastEventParamPtrs{}
	}
	mmSelectLastEvent.defaultExpectation.paramPtrs.ctx = &ctx
	mmSelectLastEvent.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSelectLastEvent
}

// ExpectShipmentIDParam2 sets up expected param shipmentID for Repository.SelectLastEvent
func (mmSelectLastEvent *mRepositoryMockSelectLastEvent) ExpectShipmentIDParam2(shipmentID uuid.UUID) *mRepositoryMockSelectLastEvent {
	if mmSelectLastEvent.mock.funcSelectLastEvent != nil {
		mmSelectLastEvent.mock.t.Fatalf("RepositoryMock.SelectLastEvent mock is already set by Set")
	}

	if mmSelectLastEvent.defaultExpectation == nil {
		mmSelectLastEvent.defaultExpectation = &RepositoryMockSelectLastEventExpectation{}
	}

	if mmSelectLastEvent.defaultExpectation.params != nil {
		mmSelectLastEvent.mock.t.Fatalf("RepositoryMock.SelectLastEvent mock is already set by Expect")
	}

	if mmSelectLastEvent.defaultExpectation.paramPtrs == nil {
		mmSelectLastEvent.defaultExpectation.paramPtrs = &RepositoryMockSelectLastEventParamPtrs{}
	}
	mmSelectLastEvent.defaultExpectation.paramPtrs.shipmentID = &shipmentID
	mmSelectLastEvent.defaultExpectation.expectationOrigins.originShipmentID = minimock.CallerInfo(1)

	return mmSelectLastEvent
}

// Inspect accepts an inspector function that has same arguments as the Repository.SelectLastEvent
func (mmSelectLastEvent *mRepositoryMockSelectLastEvent) Inspect(f func(ctx context.Context, shipmentID uuid.UUID)) *mRepositoryMockSelectLastEvent {
	if mmSelectLastEvent.mock.inspectFuncSelectLastEvent != nil {
		mmSelectLastEvent.mock.t.Fatalf("Inspect function is already set for RepositoryMock.SelectLastEvent")
	}

	mmSelectLastEvent.mock.inspectFuncSelectLastEvent = f

	return mmSelectLastEvent
}

// Return sets up results that will be returned by Repository.SelectLastEvent
func (mmSelectLastEvent *mRepositoryMockSelectLastEvent) Return(s1 shipmentrepository.SelectEventOutput, err error) *RepositoryMock {
	if mmSelectLastEvent.mock.funcSelectLastEvent != nil {
		mmSelectLastEvent.mock.t.Fatalf("RepositoryMock.SelectLastEvent mock is already set by Set")
	}

	if mmSelectLastEvent.defaultExpectation == nil {
		mmSelectLastEvent.defaultExpectation = &RepositoryMockSelectLastEventExpectation{mock: mmSelectLastEvent.mock}
	}
	mmSelectLastEvent.defaultExpectation.results = &RepositoryMockSelectLastEventResults{s1, err}
	mmSelectLastEvent.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSelectLastEvent.mock
}

// Set uses given function f to mock the Repository.SelectLastEvent method
func (mmSelectLastEvent *mRepositoryMockSelectLastEvent) Set(f func(ctx context.Context, shipmentID uuid.UUID) (s1 shipmentrepository.SelectEventOutput, err error)) *RepositoryMock {
	if mmSelectLastEvent.defaultExpectation != nil {
		mmSelectLastEvent.mock.t.Fatalf("Default expectation is already set for the Repository.SelectLastEvent method")
	}

	if len(mmSelectLastEvent.expectations) > 0 {
		mmSelectLastEvent.mock.t.Fatalf("Some expectations are already set for the Repository.SelectLastEvent method")
	}

	mmSelectLastEvent.mock.funcSelectLastEvent = f
	mmSelectLastEvent.mock.funcSelectLastEventOrigin = minimock.CallerInfo(1)
	return mmSelectLastEvent.mock
}

// When sets expectation for the Repository.SelectLastEvent which will trigger the result defined by the following
// Then helper
func (mmSelectLastEvent *mRepositoryMockSelectLastEvent) When(ctx context.Context, shipmentID uuid.UUID) *RepositoryMockSelectLastEventExpectation {
	if mmSelectLastEvent.mock.funcSelectLastEvent != nil {
		mmSelectLastEvent.mock.t.Fatalf("RepositoryMock.SelectLastEvent mock is already set by Set")
	}

	expectation := &RepositoryMockSelectLastEventExpectation{
		mock:               mmSelectLastEvent.mock,
		params:             &RepositoryMockSelectLastEventParams{ctx, shipmentID},
		expectationOrigins: RepositoryMockSelectLastEventExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSelectLastEvent.expectations = append(mmSelectLastEvent.expectations, expectation)
	return expectation
}

// Then sets up Repository.SelectLastEvent return parameters for the expectation previously defined by the When method
func (e *RepositoryMockSelectLastEventExpectation) Then(s1 shipmentrepository.SelectEventOutput, err error) *RepositoryMock {
	e.results = &RepositoryMockSelectLastEventResults{s1, err}
	return e.mock
}

// Times sets number of times Repository.SelectLastEvent should be invoked
func (mmSelectLastEvent *mRepositoryMockSelectLastEvent) Times(n uint64) *mRepositoryMockSelectLastEvent {
	if n == 0 {
		mmSelectLastEvent.mock.t.Fatalf("Times of RepositoryMock.SelectLastEvent mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSelectLastEvent.expectedInvocations, n)
	mmSelectLastEvent.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSelectLastEvent
}

func (mmSelectLastEvent *mRepositoryMockSelectLastEvent) invocationsDone() bool {
	if len(mmSelectLastEvent.expectations) == 0 && mmSelectLastEvent.defaultExpectation == nil && mmSelectLastEvent.mock.funcSelectLastEvent == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSelectLastEvent.mock.afterSelectLastEventCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSelectLastEvent.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SelectLastEvent implements Repository
func (mmSelectLastEvent *RepositoryMock) SelectLastEvent(ctx context.Context, shipmentID uuid.UUID) (s1 shipmentrepository.SelectEventOutput, err error) {
	mm_atomic.AddUint64(&mmSelectLastEvent.beforeSelectLastEventCounter, 1)
	defer mm_atomic.AddUint64(&mmSelectLastEvent.afterSelectLastEventCounter, 1)

	mmSelectLastEvent.t.Helper()

	if mmSelectLastEvent.inspectFuncSelectLastEvent != nil {
		mmSelectLastEvent.inspectFuncSelectLastEvent(ctx, shipmentID)
	}

	mm_params := RepositoryMockSelectLastEventParams{ctx, shipmentID}

	// Record call args
	mmSelectLastEvent.SelectLastEventMock.mutex.Lock()
	mmSelectLastEvent.SelectLastEventMock.callArgs = append(mmSelectLastEvent.SelectLastEventMock.callArgs, &mm_params)
	mmSelectLastEvent.SelectLastEventMock.mutex.Unlock()

	for _, e := range mmSelectLastEvent.SelectLastEventMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmSelectLastEvent.SelectLastEventMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSelectLastEvent.SelectLastEventMock.defaultExpectation.Counter, 1)
		mm_want := mmSelectLastEvent.SelectLastEventMock.defaultExpectation.params
		mm_want_ptrs := mmSelectLastEvent.SelectLastEventMock.defaultExpectation.paramPtrs

		mm_got := RepositoryMockSelectLastEventParams{ctx, shipmentID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSelectLastEvent.t.Errorf("RepositoryMock.SelectLastEvent got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSelectLastEvent.SelectLastEventMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.shipmentID != nil && !minimock.Equal(*mm_want_ptrs.shipmentID, mm_got.shipmentID) {
				mmSelectLastEvent.t.Errorf("RepositoryMock.SelectLastEvent got unexpected parameter shipmentID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSelectLastEvent.SelectLastEventMock.defaultExpectation.expectationOrigins.originShipmentID, *mm_want_ptrs.shipmentID, mm_got.shipmentID, minimock.Diff(*mm_want_ptrs.shipmentID, mm_got.shipmentID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSelectLastEvent.t.Errorf("RepositoryMock.SelectLastEvent got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSelectLastEvent.SelectLastEventMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSelectLastEvent.SelectLastEventMock.defaultExpectation.results
		if mm_results == nil {
			mmSelectLastEvent.t.Fatal("No results are set for the RepositoryMock.SelectLastEvent")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmSelectLastEvent.funcSelectLastEvent != nil {
		return mmSelectLastEvent.funcSelectLastEvent(ctx, shipmentID)
	}
	mmSelectLastEvent.t.Fatalf("Unexpected call to RepositoryMock.SelectLastEvent. %v %v", ctx, shipmentID)
	return
}

// SelectLastEventAfterCounter returns a count of finished RepositoryMock.SelectLastEvent invocations
func (mmSelectLastEvent *RepositoryMock) SelectLastEventAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSelectLastEvent.afterSelectLastEventCounter)
}

// SelectLastEventBeforeCounter returns a count of RepositoryMock.SelectLastEvent invocations
func (mmSelectLastEvent *RepositoryMock) SelectLastEventBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSelectLastEvent.beforeSelectLastEventCounter)
}

// Calls returns a list of arguments used in each call to RepositoryMock.SelectLastEvent.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSelectLastEvent *mRepositoryMockSelectLastEvent) Calls() []*RepositoryMockSelectLastEventParams {
	mmSelectLastEvent.mutex.RLock()

	argCopy := make([]*RepositoryMockSelectLastEventParams, len(mmSelectLastEvent.callArgs))
	copy(argCopy, mmSelectLastEvent.callArgs)

	mmSelectLastEvent.mutex.RUnlock()

	return argCopy
}

// MinimockSelectLastEventDone returns true if the count of the SelectLastEvent invocations corresponds
// the number of defined expectations
func (m *RepositoryMock) MinimockSelectLastEventDone() bool {
	if m.SelectLastEventMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SelectLastEventMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SelectLastEventMock.invocationsDone()
}

// MinimockSelectLastEventInspect logs each unmet expectation
func (m *RepositoryMock) MinimockSelectLastEventInspect() {
	for _, e := range m.SelectLastEventMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepositoryMock.SelectLastEvent at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSelectLastEventCounter := mm_atomic.LoadUint64(&m.afterSelectLastEventCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SelectLastEventMock.defaultExpectation != nil && afterSelectLastEventCounter < 1 {
		if m.SelectLastEventMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RepositoryMock.SelectLastEvent at\n%s", m.SelectLastEventMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RepositoryMock.SelectLastEvent at\n%s with params: %#v", m.SelectLastEventMock.defaultExpectation.expectationOrigins.origin, *m.SelectLastEventMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSelectLastEvent != nil && afterSelectLastEventCounter < 1 {
		m.t.Errorf("Expected call to RepositoryMock.SelectLastEvent at\n%s", m.funcSelectLastEventOrigin)
	}

	if !m.SelectLastEventMock.invocationsDone() && afterSelectLastEventCounter > 0 {
		m.t.Errorf("Expected %d calls to RepositoryMock.SelectLastEvent at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SelectLastEventMock.expectedInvocations), m.SelectLastEventMock.expectedInvocationsOrigin, afterSelectLastEventCounter)
	}
}

type mRepositoryMockSelectShipment struct {
	optional           bool
	mock               *RepositoryMock
	defaultExpectation *RepositoryMockSelectShipmentExpectation
	expectations       []*RepositoryMockSelectShipmentExpectation

	callArgs []*RepositoryMockSelectShipmentParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RepositoryMockSelectShipmentExpectation specifies expectation struct of the Repository.SelectShipment
type RepositoryMockSelectShipmentExpectation struct {
	mock               *RepositoryMock
	params             *RepositoryMockSelectShipmentParams
	paramPtrs          *RepositoryMockSelectShipmentParamPtrs
	expectationOrigins RepositoryMockSelectShipmentExpectationOrigins
	results            *RepositoryMockSelectShipmentResults
	returnOrigin       string
	Counter            uint64
}

// RepositoryMockSelectShipmentParams contains parameters of the Repository.SelectShipment
type RepositoryMockSelectShipmentParams struct {
	ctx        context.Context
	shipmentID uuid.UUID
}

// RepositoryMockSelectShipmentParamPtrs contains pointers to parameters of the Repository.SelectShipment
type RepositoryMockSelectShipmentParamPtrs struct {
	ctx        *context.Context
	shipmentID *uuid.UUID
}

// RepositoryMockSelectShipmentResults contains results of the Repository.SelectShipment
type RepositoryMockSelectShipmentResults struct {
	s1  shipmentrepository.SelectShipmentOutput
	err error
}

// RepositoryMockSelectShipmentOrigins contains origins of expectations of the Repository.SelectShipment
type RepositoryMockSelectShipmentExpectationOrigins struct {
	origin           string
	originCtx        string
	originShipmentID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSelectShipment *mRepositoryMockSelectShipment) Optional() *mRepositoryMockSelectShipment {
	mmSelectShipment.optional = true
	return mmSelectShipment
}

// Expect sets up expected params for Repository.SelectShipment
func (mmSelectShipment *mRepositoryMockSelectShipment) Expect(ctx context.Context, shipmentID uuid.UUID) *mRepositoryMockSelectShipment {
	if mmSelectShipment.mock.funcSelectShipment != nil {
		mmSelectShipment.mock.t.Fatalf("RepositoryMock.SelectShipment mock is already set by Set")
	}

	if mmSelectShipment.defaultExpectation == nil {
		mmSelectShipment.defaultExpectation = &RepositoryMockSelectShipmentExpectation{}
	}

	if mmSelectShipment.defaultExpectation.paramPtrs != nil {
		mmSelectShipment.mock.t.Fatalf("RepositoryMock.SelectShipment mock is already set by ExpectParams functions")
	}

	mmSelectShipment.defaultExpectation.params = &RepositoryMockSelectShipmentParams{ctx, shipmentID}
	mmSelectShipment.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSelectShipment.expectations {
		if minimock.Equal(e.params, mmSelectShipment.defaultExpectation.params) {
			mmSelectShipment.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSelectShipment.defaultExpectation.params)
		}
	}

	return mmSelectShipment
}

// ExpectCtxParam1 sets up expected param ctx for Repository.SelectShipment
func (mmSelectShipment *mRepositoryMockSelectShipment) ExpectCtxParam1(ctx context.Context) *mRepositoryMockSelectShipment {
	if mmSelectShipment.mock.funcSelectShipment != nil {
		mmSelectShipment.mock.t.Fatalf("RepositoryMock.SelectShipment mock is already set by Set")
	}

	if mmSelectShipment.defaultExpectation == nil {
		mmSelectShipment.defaultExpectation = &RepositoryMockSelectShipmentExpectation{}
	}

	if mmSelectShipment.defaultExpectation.params != nil {
		mmSelectShipment.mock.t.Fatalf("RepositoryMock.SelectShipment mock is already set by Expect")
	}

	if mmSelectShipment.defaultExpectation.paramPtrs == nil {
		mmSelectShipment.defaultExpectation.paramPtrs = &RepositoryMockSelectShipmentParamPtrs{}
	}
	mmSelectShipment.defaultExpectation.paramPtrs.ctx = &ctx
	mmSelectShipment.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSelectShipment
}

// ExpectShipmentIDParam2 sets up expected param shipmentID for Repository.SelectShipment
func (mmSelectShipment *mRepositoryMockSelectShipment) ExpectShipmentIDParam2(shipmentID uuid.UUID) *mRepositoryMockSelectShipment {
	if mmSelectShipment.mock.funcSelectShipment != nil {
		mmSelectShipment.mock.t.Fatalf("RepositoryMock.SelectShipment mock is already set by Set")
	}

	if mmSelectShipment.defaultExpectation == nil {
		mmSelectShipment.defaultExpectation = &RepositoryMockSelectShipmentExpectation{}
	}

	if mmSelectShipment.defaultExpectation.params != nil {
		mmSelectShipment.mock.t.Fatalf("RepositoryMock.SelectShipment mock is already set by Expect")
	}

	if mmSelectShipment.defaultExpectation.paramPtrs == nil {
		mmSelectShipment.defaultExpectation.paramPtrs = &RepositoryMockSelectShipmentParamPtrs{}
	}
	mmSelectShipment.defaultExpectation.paramPtrs.shipmentID = &shipmentID
	mmSelectShipment.defaultExpectation.expectationOrigins.originShipmentID = minimock.CallerInfo(1)

	return mmSelectShipment
}

// Inspect accepts an inspector function that has same arguments as the Repository.SelectShipment
func (mmSelectShipment *mRepositoryMockSelectShipment) Inspect(f func(ctx context.Context, shipmentID uuid.UUID)) *mRepositoryMockSelectShipment {
	if mmSelectShipment.mock.inspectFuncSelectShipment != nil {
		mmSelectShipment.mock.t.Fatalf("Inspect function is already set for RepositoryMock.SelectShipment")
	}

	mmSelectShipment.mock.inspectFuncSelectShipment = f

	return mmSelectShipment
}

// Return sets up results that will be returned by Repository.SelectShipment
func (mmSelectShipment *mRepositoryMockSelectShipment) Return(s1 shipmentrepository.SelectShipmentOutput, err error) *RepositoryMock {
	if mmSelectShipment.mock.funcSelectShipment != nil {
		mmSelectShipment.mock.t.Fatalf("RepositoryMock.SelectShipment mock is already set by Set")
	}

	if mmSelectShipment.defaultExpectation == nil {
		mmSelectShipment.defaultExpectation = &RepositoryMockSelectShipmentExpectation{mock: mmSelectShipment.mock}
	}
	mmSelectShipment.defaultExpectation.results = &RepositoryMockSelectShipmentResults{s1, err}
	mmSelectShipment.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSelectShipment.mock
}

// Set uses given function f to mock the Repository.SelectShipment method
func (mmSelectShipment *mRepositoryMockSelectShipment) Set(f func(ctx context.Context, shipmentID uuid.UUID) (s1 shipmentrepository.SelectShipmentOutput, err error)) *RepositoryMock {
	if mmSelectShipment.defaultExpectation != nil {
		mmSelectShipment.mock.t.Fatalf("Default expectation is already set for the Repository.SelectShipment method")
	}

	if len(mmSelectShipment.expectations) > 0 {
		mmSelectShipment.mock.t.Fatalf("Some expectations are already set for the Repository.SelectShipment method")
	}

	mmSelectShipment.mock.funcSelectShipment = f
	mmSelectShipment.mock.funcSelectShipmentOrigin = minimock.CallerInfo(1)
	return mmSelectShipment.mock
}

// When sets expectation for the Repository.SelectShipment which will trigger the result defined by the following
// Then helper
func (mmSelectShipment *mRepositoryMockSelectShipment) When(ctx context.Context, shipmentID uuid.UUID) *RepositoryMockSelectShipmentExpectation {
	if mmSelectShipment.mock.funcSelectShipment != nil {
		mmSelectShipment.mock.t.Fatalf("RepositoryMock.SelectShipment mock is already set by Set")
	}

	expectation := &RepositoryMockSelectShipmentExpectation{
		mock:               mmSelectShipment.mock,
		params:             &RepositoryMockSelectShipmentParams{ctx, shipmentID},
		expectationOrigins: RepositoryMockSelectShipmentExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSelectShipment.expectations = append(mmSelectShipment.expectations, expectation)
	return expectation
}

// Then sets up Repository.SelectShipment return parameters for the expectation previously defined by the When method
func (e *RepositoryMockSelectShipmentExpectation) Then(s1 shipmentrepository.SelectShipmentOutput, err error) *RepositoryMock {
	e.results = &RepositoryMockSelectShipmentResults{s1, err}
	return e.mock
}

// Times sets number of times Repository.SelectShipment should be invoked
func (mmSelectShipment *mRepositoryMockSelectShipment) Times(n uint64) *mRepositoryMockSelectShipment {
	if n == 0 {
		mmSelectShipment.mock.t.Fatalf("Times of RepositoryMock.SelectShipment mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSelectShipment.expectedInvocations, n)
	mmSelectShipment.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSelectShipment
}

func (mmSelectShipment *mRepositoryMockSelectShipment) invocationsDone() bool {
	if len(mmSelectShipment.expectations) == 0 && mmSelectShipment.defaultExpectation == nil && mmSelectShipment.mock.funcSelectShipment == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSelectShipment.mock.afterSelectShipmentCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSelectShipment.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SelectShipment implements Repository
func (mmSelectShipment *RepositoryMock) SelectShipment(ctx context.Context, shipmentID uuid.UUID) (s1 shipmentrepository.SelectShipmentOutput, err error) {
	mm_atomic.AddUint64(&mmSelectShipment.beforeSelectShipmentCounter, 1)
	defer mm_atomic.AddUint64(&mmSelectShipment.afterSelectShipmentCounter, 1)

	mmSelectShipment.t.Helper()

	if mmSelectShipment.inspectFuncSelectShipment != nil {
		mmSelectShipment.inspectFuncSelectShipment(ctx, shipmentID)
	}

	mm_params := RepositoryMockSelectShipmentParams{ctx, shipmentID}

	// Record call args
	mmSelectShipment.SelectShipmentMock.mutex.Lock()
	mmSelectShipment.SelectShipmentMock.callArgs = append(mmSelectShipment.SelectShipmentMock.callArgs, &mm_params)
	mmSelectShipment.SelectShipmentMock.mutex.Unlock()

	for _, e := range mmSelectShipment.SelectShipmentMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmSelectShipment.SelectShipmentMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSelectShipment.SelectShipmentMock.defaultExpectation.Counter, 1)
		mm_want := mmSelectShipment.SelectShipmentMock.defaultExpectation.params
		mm_want_ptrs := mmSelectShipment.SelectShipmentMock.defaultExpectation.paramPtrs

		mm_got := RepositoryMockSelectShipmentParams{ctx, shipmentID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSelectShipment.t.Errorf("RepositoryMock.SelectShipment got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSelectShipment.SelectShipmentMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.shipmentID != nil && !minimock.Equal(*mm_want_ptrs.shipmentID, mm_got.shipmentID) {
				mmSelectShipment.t.Errorf("RepositoryMock.SelectShipment got unexpected parameter shipmentID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSelectShipment.SelectShipmentMock.defaultExpectation.expectationOrigins.originShipmentID, *mm_want_ptrs.shipmentID, mm_got.shipmentID, minimock.Diff(*mm_want_ptrs.shipmentID, mm_got.shipmentID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSelectShipment.t.Errorf("RepositoryMock.SelectShipment got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSelectShipment.SelectShipmentMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSelectShipment.SelectShipmentMock.defaultExpectation.results
		if mm_results == nil {
			mmSelectShipment.t.Fatal("No results are set for the RepositoryMock.SelectShipment")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmSelectShipment.funcSelectShipment != nil {
		return mmSelectShipment.funcSelectShipment(ctx, shipmentID)
	}
	mmSelectShipment.t.Fatalf("Unexpected call to RepositoryMock.SelectShipment. %v %v", ctx, shipmentID)
	return
}

// SelectShipmentAfterCounter returns a count of finished RepositoryMock.SelectShipment invocations
func (mmSelectShipment *RepositoryMock) SelectShipmentAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSelectShipment.afterSelectShipmentCounter)
}

// SelectShipmentBeforeCounter returns a count of RepositoryMock.SelectShipment invocations
func (mmSelectShipment *RepositoryMock) SelectShipmentBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSelectShipment.beforeSelectShipmentCounter)
}

// Calls returns a list of arguments used in each call to RepositoryMock.SelectShipment.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSelectShipment *mRepositoryMockSelectShipment) Calls() []*RepositoryMockSelectShipmentParams {
	mmSelectShipment.mutex.RLock()

	argCopy := make([]*RepositoryMockSelectShipmentParams, len(mmSelectShipment.callArgs))
	copy(argCopy, mmSelectShipment.callArgs)

	mmSelectShipment.mutex.RUnlock()

	return argCopy
}

// MinimockSelectShipmentDone returns true if the count of the SelectShipment invocations corresponds
// the number of defined expectations
func (m *RepositoryMock) MinimockSelectShipmentDone() bool {
	if m.SelectShipmentMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SelectShipmentMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SelectShipmentMock.invocationsDone()
}

// MinimockSelectShipmentInspect logs each unmet expectation
func (m *RepositoryMock) MinimockSelectShipmentInspect() {
	for _, e := range m.SelectShipmentMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepositoryMock.SelectShipment at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSelectShipmentCounter := mm_atomic.LoadUint64(&m.afterSelectShipmentCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SelectShipmentMock.defaultExpectation != nil && afterSelectShipmentCounter < 1 {
		if m.SelectShipmentMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RepositoryMock.SelectShipment at\n%s", m.SelectShipmentMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RepositoryMock.SelectShipment at\n%s with params: %#v", m.SelectShipmentMock.defaultExpectation.expectationOrigins.origin, *m.SelectShipmentMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSelectShipment != nil && afterSelectShipmentCounter < 1 {
		m.t.Errorf("Expected call to RepositoryMock.SelectShipment at\n%s", m.funcSelectShipmentOrigin)
	}

	if !m.SelectShipmentMock.invocationsDone() && afterSelectShipmentCounter > 0 {
		m.t.Errorf("Expected %d calls to RepositoryMock.SelectShipment at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SelectShipmentMock.expectedInvocations), m.SelectShipmentMock.expectedInvocationsOrigin, afterSelectShipmentCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockInsertEventInspect()

			m.MinimockInsertShipmentInspect()

			m.MinimockSelectEventsInspect()

			m.MinimockSelectLastEventInspect()

			m.MinimockSelectShipmentInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockInsertEventDone() &&
		m.MinimockInsertShipmentDone() &&
		m.MinimockSelectEventsDone() &&
		m.MinimockSelectLastEventDone() &&
		m.MinimockSelectShipmentDone()
}
