// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: shipment.proto

package shipmentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShipmentStatus int32

const (
	ShipmentStatus_SHIPMENT_STATUS_PENDING           ShipmentStatus = 0
	ShipmentStatus_SHIPMENT_STATUS_AWAITING_DRIVER   ShipmentStatus = 1
	ShipmentStatus_SHIPMENT_STATUS_PICKED_UP         ShipmentStatus = 2
	ShipmentStatus_SHIPMENT_STATUS_IN_TRANSIT        ShipmentStatus = 3
	ShipmentStatus_SHIPMENT_STATUS_DELAYED           ShipmentStatus = 4
	ShipmentStatus_SHIPMENT_STATUS_AT_TRANSFER_POINT ShipmentStatus = 5
	ShipmentStatus_SHIPMENT_STATUS_DELIVERED         ShipmentStatus = 6
	ShipmentStatus_SHIPMENT_STATUS_CANCELLED         ShipmentStatus = 7
)

// Enum value maps for ShipmentStatus.
var (
	ShipmentStatus_name = map[int32]string{
		0: "SHIPMENT_STATUS_PENDING",
		1: "SHIPMENT_STATUS_AWAITING_DRIVER",
		2: "SHIPMENT_STATUS_PICKED_UP",
		3: "SHIPMENT_STATUS_IN_TRANSIT",
		4: "SHIPMENT_STATUS_DELAYED",
		5: "SHIPMENT_STATUS_AT_TRANSFER_POINT",
		6: "SHIPMENT_STATUS_DELIVERED",
		7: "SHIPMENT_STATUS_CANCELLED",
	}
	ShipmentStatus_value = map[string]int32{
		"SHIPMENT_STATUS_PENDING":           0,
		"SHIPMENT_STATUS_AWAITING_DRIVER":   1,
		"SHIPMENT_STATUS_PICKED_UP":         2,
		"SHIPMENT_STATUS_IN_TRANSIT":        3,
		"SHIPMENT_STATUS_DELAYED":           4,
		"SHIPMENT_STATUS_AT_TRANSFER_POINT": 5,
		"SHIPMENT_STATUS_DELIVERED":         6,
		"SHIPMENT_STATUS_CANCELLED":         7,
	}
)

func (x ShipmentStatus) Enum() *ShipmentStatus {
	p := new(ShipmentStatus)
	*p = x
	return p
}

func (x ShipmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShipmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shipment_proto_enumTypes[0].Descriptor()
}

func (ShipmentStatus) Type() protoreflect.EnumType {
	return &file_shipment_proto_enumTypes[0]
}

func (x ShipmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShipmentStatus.Descriptor instead.
func (ShipmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{0}
}

type Shipment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,2,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	Origin          string                 `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination     string                 `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	Status          ShipmentStatus         `protobuf:"varint,5,opt,name=status,proto3,enum=shipment.v1.ShipmentStatus" json:"status,omitempty"`
	DriverName      string                 `protobuf:"bytes,6,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	UnitNumber      string                 `protobuf:"bytes,7,opt,name=unit_number,json=unitNumber,proto3" json:"unit_number,omitempty"`
	ShipmentAmount  int64                  `protobuf:"varint,8,opt,name=shipment_amount,json=shipmentAmount,proto3" json:"shipment_amount,omitempty"`
	DriverRevenue   int64                  `protobuf:"varint,9,opt,name=driver_revenue,json=driverRevenue,proto3" json:"driver_revenue,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Shipment) Reset() {
	*x = Shipment{}
	mi := &file_shipment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shipment) ProtoMessage() {}

func (x *Shipment) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shipment.ProtoReflect.Descriptor instead.
func (*Shipment) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{0}
}

func (x *Shipment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shipment) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *Shipment) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Shipment) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Shipment) GetStatus() ShipmentStatus {
	if x != nil {
		return x.Status
	}
	return ShipmentStatus_SHIPMENT_STATUS_PENDING
}

func (x *Shipment) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *Shipment) GetUnitNumber() string {
	if x != nil {
		return x.UnitNumber
	}
	return ""
}

func (x *Shipment) GetShipmentAmount() int64 {
	if x != nil {
		return x.ShipmentAmount
	}
	return 0
}

func (x *Shipment) GetDriverRevenue() int64 {
	if x != nil {
		return x.DriverRevenue
	}
	return 0
}

func (x *Shipment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Shipment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ShipmentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShipmentId    string                 `protobuf:"bytes,2,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	Status        ShipmentStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=shipment.v1.ShipmentStatus" json:"status,omitempty"`
	Details       string                 `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentEvent) Reset() {
	*x = ShipmentEvent{}
	mi := &file_shipment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentEvent) ProtoMessage() {}

func (x *ShipmentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentEvent.ProtoReflect.Descriptor instead.
func (*ShipmentEvent) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{1}
}

func (x *ShipmentEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShipmentEvent) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *ShipmentEvent) GetStatus() ShipmentStatus {
	if x != nil {
		return x.Status
	}
	return ShipmentStatus_SHIPMENT_STATUS_PENDING
}

func (x *ShipmentEvent) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *ShipmentEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

type CreateShipmentRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ReferenceNumber     string                 `protobuf:"bytes,1,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	Origin              string                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination         string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	DriverName          string                 `protobuf:"bytes,4,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	UnitNumber          string                 `protobuf:"bytes,5,opt,name=unit_number,json=unitNumber,proto3" json:"unit_number,omitempty"`
	ShipmentAmountCents int64                  `protobuf:"varint,6,opt,name=shipment_amount_cents,json=shipmentAmountCents,proto3" json:"shipment_amount_cents,omitempty"`
	DriverRevenueCents  int64                  `protobuf:"varint,7,opt,name=driver_revenue_cents,json=driverRevenueCents,proto3" json:"driver_revenue_cents,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateShipmentRequest) Reset() {
	*x = CreateShipmentRequest{}
	mi := &file_shipment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentRequest) ProtoMessage() {}

func (x *CreateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentRequest.ProtoReflect.Descriptor instead.
func (*CreateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShipmentRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *CreateShipmentRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *CreateShipmentRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CreateShipmentRequest) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *CreateShipmentRequest) GetUnitNumber() string {
	if x != nil {
		return x.UnitNumber
	}
	return ""
}

func (x *CreateShipmentRequest) GetShipmentAmountCents() int64 {
	if x != nil {
		return x.ShipmentAmountCents
	}
	return 0
}

func (x *CreateShipmentRequest) GetDriverRevenueCents() int64 {
	if x != nil {
		return x.DriverRevenueCents
	}
	return 0
}

type CreateShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentResponse) Reset() {
	*x = CreateShipmentResponse{}
	mi := &file_shipment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentResponse) ProtoMessage() {}

func (x *CreateShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentResponse.ProtoReflect.Descriptor instead.
func (*CreateShipmentResponse) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{3}
}

func (x *CreateShipmentResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

type GetShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentRequest) Reset() {
	*x = GetShipmentRequest{}
	mi := &file_shipment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentRequest) ProtoMessage() {}

func (x *GetShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{4}
}

func (x *GetShipmentRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

type GetShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentResponse) Reset() {
	*x = GetShipmentResponse{}
	mi := &file_shipment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentResponse) ProtoMessage() {}

func (x *GetShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentResponse.ProtoReflect.Descriptor instead.
func (*GetShipmentResponse) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{5}
}

func (x *GetShipmentResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

type AddShipmentEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	Status        ShipmentStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=shipment.v1.ShipmentStatus" json:"status,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddShipmentEventRequest) Reset() {
	*x = AddShipmentEventRequest{}
	mi := &file_shipment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddShipmentEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShipmentEventRequest) ProtoMessage() {}

func (x *AddShipmentEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShipmentEventRequest.ProtoReflect.Descriptor instead.
func (*AddShipmentEventRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{6}
}

func (x *AddShipmentEventRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *AddShipmentEventRequest) GetStatus() ShipmentStatus {
	if x != nil {
		return x.Status
	}
	return ShipmentStatus_SHIPMENT_STATUS_PENDING
}

func (x *AddShipmentEventRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type AddShipmentEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *ShipmentEvent         `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddShipmentEventResponse) Reset() {
	*x = AddShipmentEventResponse{}
	mi := &file_shipment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddShipmentEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShipmentEventResponse) ProtoMessage() {}

func (x *AddShipmentEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShipmentEventResponse.ProtoReflect.Descriptor instead.
func (*AddShipmentEventResponse) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{7}
}

func (x *AddShipmentEventResponse) GetEvent() *ShipmentEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type GetShipmentEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentEventsRequest) Reset() {
	*x = GetShipmentEventsRequest{}
	mi := &file_shipment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentEventsRequest) ProtoMessage() {}

func (x *GetShipmentEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentEventsRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentEventsRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{8}
}

func (x *GetShipmentEventsRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

type GetShipmentEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*ShipmentEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentEventsResponse) Reset() {
	*x = GetShipmentEventsResponse{}
	mi := &file_shipment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentEventsResponse) ProtoMessage() {}

func (x *GetShipmentEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentEventsResponse.ProtoReflect.Descriptor instead.
func (*GetShipmentEventsResponse) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{9}
}

func (x *GetShipmentEventsResponse) GetEvents() []*ShipmentEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_shipment_proto protoreflect.FileDescriptor

const file_shipment_proto_rawDesc = "" +
	"\n" +
	"\x0eshipment.proto\x12\vshipment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbc\x03\n" +
	"\bShipment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10reference_number\x18\x02 \x01(\tR\x0freferenceNumber\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x04 \x01(\tR\vdestination\x123\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1b.shipment.v1.ShipmentStatusR\x06status\x12\x1f\n" +
	"\vdriver_name\x18\x06 \x01(\tR\n" +
	"driverName\x12\x1f\n" +
	"\vunit_number\x18\a \x01(\tR\n" +
	"unitNumber\x12'\n" +
	"\x0fshipment_amount\x18\b \x01(\x03R\x0eshipmentAmount\x12%\n" +
	"\x0edriver_revenue\x18\t \x01(\x03R\rdriverRevenue\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xcc\x01\n" +
	"\rShipmentEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vshipment_id\x18\x02 \x01(\tR\n" +
	"shipmentId\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.shipment.v1.ShipmentStatusR\x06status\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xa4\x02\n" +
	"\x15CreateShipmentRequest\x12)\n" +
	"\x10reference_number\x18\x01 \x01(\tR\x0freferenceNumber\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12\x1f\n" +
	"\vdriver_name\x18\x04 \x01(\tR\n" +
	"driverName\x12\x1f\n" +
	"\vunit_number\x18\x05 \x01(\tR\n" +
	"unitNumber\x122\n" +
	"\x15shipment_amount_cents\x18\x06 \x01(\x03R\x13shipmentAmountCents\x120\n" +
	"\x14driver_revenue_cents\x18\a \x01(\x03R\x12driverRevenueCents\"K\n" +
	"\x16CreateShipmentResponse\x121\n" +
	"\bshipment\x18\x01 \x01(\v2\x15.shipment.v1.ShipmentR\bshipment\"5\n" +
	"\x12GetShipmentRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\"H\n" +
	"\x13GetShipmentResponse\x121\n" +
	"\bshipment\x18\x01 \x01(\v2\x15.shipment.v1.ShipmentR\bshipment\"\x89\x01\n" +
	"\x17AddShipmentEventRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.shipment.v1.ShipmentStatusR\x06status\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"L\n" +
	"\x18AddShipmentEventResponse\x120\n" +
	"\x05event\x18\x01 \x01(\v2\x1a.shipment.v1.ShipmentEventR\x05event\";\n" +
	"\x18GetShipmentEventsRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\"O\n" +
	"\x19GetShipmentEventsResponse\x122\n" +
	"\x06events\x18\x01 \x03(\v2\x1a.shipment.v1.ShipmentEventR\x06events*\x93\x02\n" +
	"\x0eShipmentStatus\x12\x1b\n" +
	"\x17SHIPMENT_STATUS_PENDING\x10\x00\x12#\n" +
	"\x1fSHIPMENT_STATUS_AWAITING_DRIVER\x10\x01\x12\x1d\n" +
	"\x19SHIPMENT_STATUS_PICKED_UP\x10\x02\x12\x1e\n" +
	"\x1aSHIPMENT_STATUS_IN_TRANSIT\x10\x03\x12\x1b\n" +
	"\x17SHIPMENT_STATUS_DELAYED\x10\x04\x12%\n" +
	"!SHIPMENT_STATUS_AT_TRANSFER_POINT\x10\x05\x12\x1d\n" +
	"\x19SHIPMENT_STATUS_DELIVERED\x10\x06\x12\x1d\n" +
	"\x19SHIPMENT_STATUS_CANCELLED\x10\a2\x83\x03\n" +
	"\x0fShipmentService\x12Y\n" +
	"\x0eCreateShipment\x12\".shipment.v1.CreateShipmentRequest\x1a#.shipment.v1.CreateShipmentResponse\x12P\n" +
	"\vGetShipment\x12\x1f.shipment.v1.GetShipmentRequest\x1a .shipment.v1.GetShipmentResponse\x12_\n" +
	"\x10AddShipmentEvent\x12$.shipment.v1.AddShipmentEventRequest\x1a%.shipment.v1.AddShipmentEventResponse\x12b\n" +
	"\x11GetShipmentEvents\x12%.shipment.v1.GetShipmentEventsRequest\x1a&.shipment.v1.GetShipmentEventsResponseB,Z*vektor-init/pkg/api/shipment/v1;shipmentpbb\x06proto3"

var (
	file_shipment_proto_rawDescOnce sync.Once
	file_shipment_proto_rawDescData []byte
)

func file_shipment_proto_rawDescGZIP() []byte {
	file_shipment_proto_rawDescOnce.Do(func() {
		file_shipment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipment_proto_rawDesc), len(file_shipment_proto_rawDesc)))
	})
	return file_shipment_proto_rawDescData
}

var file_shipment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shipment_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_shipment_proto_goTypes = []any{
	(ShipmentStatus)(0),               // 0: shipment.v1.ShipmentStatus
	(*Shipment)(nil),                  // 1: shipment.v1.Shipment
	(*ShipmentEvent)(nil),             // 2: shipment.v1.ShipmentEvent
	(*CreateShipmentRequest)(nil),     // 3: shipment.v1.CreateShipmentRequest
	(*CreateShipmentResponse)(nil),    // 4: shipment.v1.CreateShipmentResponse
	(*GetShipmentRequest)(nil),        // 5: shipment.v1.GetShipmentRequest
	(*GetShipmentResponse)(nil),       // 6: shipment.v1.GetShipmentResponse
	(*AddShipmentEventRequest)(nil),   // 7: shipment.v1.AddShipmentEventRequest
	(*AddShipmentEventResponse)(nil),  // 8: shipment.v1.AddShipmentEventResponse
	(*GetShipmentEventsRequest)(nil),  // 9: shipment.v1.GetShipmentEventsRequest
	(*GetShipmentEventsResponse)(nil), // 10: shipment.v1.GetShipmentEventsResponse
	(*timestamppb.Timestamp)(nil),     // 11: google.protobuf.Timestamp
}
var file_shipment_proto_depIdxs = []int32{
	0,  // 0: shipment.v1.Shipment.status:type_name -> shipment.v1.ShipmentStatus
	11, // 1: shipment.v1.Shipment.created_at:type_name -> google.protobuf.Timestamp
	11, // 2: shipment.v1.Shipment.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: shipment.v1.ShipmentEvent.status:type_name -> shipment.v1.ShipmentStatus
	11, // 4: shipment.v1.ShipmentEvent.occurred_at:type_name -> google.protobuf.Timestamp
	1,  // 5: shipment.v1.CreateShipmentResponse.shipment:type_name -> shipment.v1.Shipment
	1,  // 6: shipment.v1.GetShipmentResponse.shipment:type_name -> shipment.v1.Shipment
	0,  // 7: shipment.v1.AddShipmentEventRequest.status:type_name -> shipment.v1.ShipmentStatus
	2,  // 8: shipment.v1.AddShipmentEventResponse.event:type_name -> shipment.v1.ShipmentEvent
	2,  // 9: shipment.v1.GetShipmentEventsResponse.events:type_name -> shipment.v1.ShipmentEvent
	3,  // 10: shipment.v1.ShipmentService.CreateShipment:input_type -> shipment.v1.CreateShipmentRequest
	5,  // 11: shipment.v1.ShipmentService.GetShipment:input_type -> shipment.v1.GetShipmentRequest
	7,  // 12: shipment.v1.ShipmentService.AddShipmentEvent:input_type -> shipment.v1.AddShipmentEventRequest
	9,  // 13: shipment.v1.ShipmentService.GetShipmentEvents:input_type -> shipment.v1.GetShipmentEventsRequest
	4,  // 14: shipment.v1.ShipmentService.CreateShipment:output_type -> shipment.v1.CreateShipmentResponse
	6,  // 15: shipment.v1.ShipmentService.GetShipment:output_type -> shipment.v1.GetShipmentResponse
	8,  // 16: shipment.v1.ShipmentService.AddShipmentEvent:output_type -> shipment.v1.AddShipmentEventResponse
	10, // 17: shipment.v1.ShipmentService.GetShipmentEvents:output_type -> shipment.v1.GetShipmentEventsResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_shipment_proto_init() }
func file_shipment_proto_init() {
	if File_shipment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipment_proto_rawDesc), len(file_shipment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipment_proto_goTypes,
		DependencyIndexes: file_shipment_proto_depIdxs,
		EnumInfos:         file_shipment_proto_enumTypes,
		MessageInfos:      file_shipment_proto_msgTypes,
	}.Build()
	File_shipment_proto = out.File
	file_shipment_proto_goTypes = nil
	file_shipment_proto_depIdxs = nil
}
