// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: shipment.proto

package shipmentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShipmentStatus int32

const (
	ShipmentStatus_Unknown         ShipmentStatus = 0
	ShipmentStatus_Pending         ShipmentStatus = 1
	ShipmentStatus_AwaitingDriver  ShipmentStatus = 2
	ShipmentStatus_PickedUp        ShipmentStatus = 3
	ShipmentStatus_InTransit       ShipmentStatus = 4
	ShipmentStatus_Delayed         ShipmentStatus = 5
	ShipmentStatus_AtTransferPoint ShipmentStatus = 6
	ShipmentStatus_Delivered       ShipmentStatus = 7
	ShipmentStatus_Cancelled       ShipmentStatus = 8
)

// Enum value maps for ShipmentStatus.
var (
	ShipmentStatus_name = map[int32]string{
		0: "Unknown",
		1: "Pending",
		2: "AwaitingDriver",
		3: "PickedUp",
		4: "InTransit",
		5: "Delayed",
		6: "AtTransferPoint",
		7: "Delivered",
		8: "Cancelled",
	}
	ShipmentStatus_value = map[string]int32{
		"Unknown":         0,
		"Pending":         1,
		"AwaitingDriver":  2,
		"PickedUp":        3,
		"InTransit":       4,
		"Delayed":         5,
		"AtTransferPoint": 6,
		"Delivered":       7,
		"Cancelled":       8,
	}
)

func (x ShipmentStatus) Enum() *ShipmentStatus {
	p := new(ShipmentStatus)
	*p = x
	return p
}

func (x ShipmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShipmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shipment_proto_enumTypes[0].Descriptor()
}

func (ShipmentStatus) Type() protoreflect.EnumType {
	return &file_shipment_proto_enumTypes[0]
}

func (x ShipmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShipmentStatus.Descriptor instead.
func (ShipmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{0}
}

type Shipment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,2,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	Origin          string                 `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination     string                 `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	DriverName      string                 `protobuf:"bytes,5,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	UnitId          string                 `protobuf:"bytes,6,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	ShipmentCost    int64                  `protobuf:"varint,7,opt,name=shipment_cost,json=shipmentCost,proto3" json:"shipment_cost,omitempty"`
	DriverRevenue   int64                  `protobuf:"varint,8,opt,name=driver_revenue,json=driverRevenue,proto3" json:"driver_revenue,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status          ShipmentStatus         `protobuf:"varint,10,opt,name=status,proto3,enum=shipment.v1.ShipmentStatus" json:"status,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Shipment) Reset() {
	*x = Shipment{}
	mi := &file_shipment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shipment) ProtoMessage() {}

func (x *Shipment) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shipment.ProtoReflect.Descriptor instead.
func (*Shipment) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{0}
}

func (x *Shipment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shipment) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *Shipment) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Shipment) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Shipment) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *Shipment) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *Shipment) GetShipmentCost() int64 {
	if x != nil {
		return x.ShipmentCost
	}
	return 0
}

func (x *Shipment) GetDriverRevenue() int64 {
	if x != nil {
		return x.DriverRevenue
	}
	return 0
}

func (x *Shipment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Shipment) GetStatus() ShipmentStatus {
	if x != nil {
		return x.Status
	}
	return ShipmentStatus_Unknown
}

func (x *Shipment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ShipmentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShipmentId    string                 `protobuf:"bytes,2,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	Status        ShipmentStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=shipment.v1.ShipmentStatus" json:"status,omitempty"`
	Details       string                 `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentEvent) Reset() {
	*x = ShipmentEvent{}
	mi := &file_shipment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentEvent) ProtoMessage() {}

func (x *ShipmentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentEvent.ProtoReflect.Descriptor instead.
func (*ShipmentEvent) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{1}
}

func (x *ShipmentEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShipmentEvent) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *ShipmentEvent) GetStatus() ShipmentStatus {
	if x != nil {
		return x.Status
	}
	return ShipmentStatus_Unknown
}

func (x *ShipmentEvent) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *ShipmentEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

type CreateShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	DriverName    string                 `protobuf:"bytes,3,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	UnitId        string                 `protobuf:"bytes,4,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	ShipmentCost  int64                  `protobuf:"varint,5,opt,name=shipment_cost,json=shipmentCost,proto3" json:"shipment_cost,omitempty"`
	DriverRevenue int64                  `protobuf:"varint,6,opt,name=driver_revenue,json=driverRevenue,proto3" json:"driver_revenue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentRequest) Reset() {
	*x = CreateShipmentRequest{}
	mi := &file_shipment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentRequest) ProtoMessage() {}

func (x *CreateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentRequest.ProtoReflect.Descriptor instead.
func (*CreateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShipmentRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *CreateShipmentRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CreateShipmentRequest) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *CreateShipmentRequest) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *CreateShipmentRequest) GetShipmentCost() int64 {
	if x != nil {
		return x.ShipmentCost
	}
	return 0
}

func (x *CreateShipmentRequest) GetDriverRevenue() int64 {
	if x != nil {
		return x.DriverRevenue
	}
	return 0
}

type CreateShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentResponse) Reset() {
	*x = CreateShipmentResponse{}
	mi := &file_shipment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentResponse) ProtoMessage() {}

func (x *CreateShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentResponse.ProtoReflect.Descriptor instead.
func (*CreateShipmentResponse) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{3}
}

func (x *CreateShipmentResponse) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

type GetShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentRequest) Reset() {
	*x = GetShipmentRequest{}
	mi := &file_shipment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentRequest) ProtoMessage() {}

func (x *GetShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{4}
}

func (x *GetShipmentRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

type GetShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentResponse) Reset() {
	*x = GetShipmentResponse{}
	mi := &file_shipment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentResponse) ProtoMessage() {}

func (x *GetShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentResponse.ProtoReflect.Descriptor instead.
func (*GetShipmentResponse) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{5}
}

func (x *GetShipmentResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

type AddShipmentEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	Status        ShipmentStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=shipment.v1.ShipmentStatus" json:"status,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddShipmentEventRequest) Reset() {
	*x = AddShipmentEventRequest{}
	mi := &file_shipment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddShipmentEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShipmentEventRequest) ProtoMessage() {}

func (x *AddShipmentEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShipmentEventRequest.ProtoReflect.Descriptor instead.
func (*AddShipmentEventRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{6}
}

func (x *AddShipmentEventRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *AddShipmentEventRequest) GetStatus() ShipmentStatus {
	if x != nil {
		return x.Status
	}
	return ShipmentStatus_Unknown
}

func (x *AddShipmentEventRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type GetShipmentEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentEventsRequest) Reset() {
	*x = GetShipmentEventsRequest{}
	mi := &file_shipment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentEventsRequest) ProtoMessage() {}

func (x *GetShipmentEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentEventsRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentEventsRequest) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{7}
}

func (x *GetShipmentEventsRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

type GetShipmentEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*ShipmentEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentEventsResponse) Reset() {
	*x = GetShipmentEventsResponse{}
	mi := &file_shipment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentEventsResponse) ProtoMessage() {}

func (x *GetShipmentEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentEventsResponse.ProtoReflect.Descriptor instead.
func (*GetShipmentEventsResponse) Descriptor() ([]byte, []int) {
	return file_shipment_proto_rawDescGZIP(), []int{8}
}

func (x *GetShipmentEventsResponse) GetEvents() []*ShipmentEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_shipment_proto protoreflect.FileDescriptor

const file_shipment_proto_rawDesc = "" +
	"\n" +
	"\x0eshipment.proto\x12\vshipment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb0\x03\n" +
	"\bShipment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10reference_number\x18\x02 \x01(\tR\x0freferenceNumber\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x04 \x01(\tR\vdestination\x12\x1f\n" +
	"\vdriver_name\x18\x05 \x01(\tR\n" +
	"driverName\x12\x17\n" +
	"\aunit_id\x18\x06 \x01(\tR\x06unitId\x12#\n" +
	"\rshipment_cost\x18\a \x01(\x03R\fshipmentCost\x12%\n" +
	"\x0edriver_revenue\x18\b \x01(\x03R\rdriverRevenue\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x123\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x1b.shipment.v1.ShipmentStatusR\x06status\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xcc\x01\n" +
	"\rShipmentEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vshipment_id\x18\x02 \x01(\tR\n" +
	"shipmentId\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.shipment.v1.ShipmentStatusR\x06status\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xd7\x01\n" +
	"\x15CreateShipmentRequest\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x1f\n" +
	"\vdriver_name\x18\x03 \x01(\tR\n" +
	"driverName\x12\x17\n" +
	"\aunit_id\x18\x04 \x01(\tR\x06unitId\x12#\n" +
	"\rshipment_cost\x18\x05 \x01(\x03R\fshipmentCost\x12%\n" +
	"\x0edriver_revenue\x18\x06 \x01(\x03R\rdriverRevenue\"9\n" +
	"\x16CreateShipmentResponse\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\"5\n" +
	"\x12GetShipmentRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\"H\n" +
	"\x13GetShipmentResponse\x121\n" +
	"\bshipment\x18\x01 \x01(\v2\x15.shipment.v1.ShipmentR\bshipment\"\x89\x01\n" +
	"\x17AddShipmentEventRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.shipment.v1.ShipmentStatusR\x06status\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\";\n" +
	"\x18GetShipmentEventsRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\"O\n" +
	"\x19GetShipmentEventsResponse\x122\n" +
	"\x06events\x18\x01 \x03(\v2\x1a.shipment.v1.ShipmentEventR\x06events*\x9b\x01\n" +
	"\x0eShipmentStatus\x12\v\n" +
	"\aUnknown\x10\x00\x12\v\n" +
	"\aPending\x10\x01\x12\x12\n" +
	"\x0eAwaitingDriver\x10\x02\x12\f\n" +
	"\bPickedUp\x10\x03\x12\r\n" +
	"\tInTransit\x10\x04\x12\v\n" +
	"\aDelayed\x10\x05\x12\x13\n" +
	"\x0fAtTransferPoint\x10\x06\x12\r\n" +
	"\tDelivered\x10\a\x12\r\n" +
	"\tCancelled\x10\b2\xf4\x02\n" +
	"\x0fShipmentService\x12Y\n" +
	"\x0eCreateShipment\x12\".shipment.v1.CreateShipmentRequest\x1a#.shipment.v1.CreateShipmentResponse\x12P\n" +
	"\vGetShipment\x12\x1f.shipment.v1.GetShipmentRequest\x1a .shipment.v1.GetShipmentResponse\x12P\n" +
	"\x10AddShipmentEvent\x12$.shipment.v1.AddShipmentEventRequest\x1a\x16.google.protobuf.Empty\x12b\n" +
	"\x11GetShipmentEvents\x12%.shipment.v1.GetShipmentEventsRequest\x1a&.shipment.v1.GetShipmentEventsResponseBCZAgithub.com/bazeeko/vektor-shipment/pkg/api/shipment/v1;shipmentpbb\x06proto3"

var (
	file_shipment_proto_rawDescOnce sync.Once
	file_shipment_proto_rawDescData []byte
)

func file_shipment_proto_rawDescGZIP() []byte {
	file_shipment_proto_rawDescOnce.Do(func() {
		file_shipment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipment_proto_rawDesc), len(file_shipment_proto_rawDesc)))
	})
	return file_shipment_proto_rawDescData
}

var file_shipment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shipment_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_shipment_proto_goTypes = []any{
	(ShipmentStatus)(0),               // 0: shipment.v1.ShipmentStatus
	(*Shipment)(nil),                  // 1: shipment.v1.Shipment
	(*ShipmentEvent)(nil),             // 2: shipment.v1.ShipmentEvent
	(*CreateShipmentRequest)(nil),     // 3: shipment.v1.CreateShipmentRequest
	(*CreateShipmentResponse)(nil),    // 4: shipment.v1.CreateShipmentResponse
	(*GetShipmentRequest)(nil),        // 5: shipment.v1.GetShipmentRequest
	(*GetShipmentResponse)(nil),       // 6: shipment.v1.GetShipmentResponse
	(*AddShipmentEventRequest)(nil),   // 7: shipment.v1.AddShipmentEventRequest
	(*GetShipmentEventsRequest)(nil),  // 8: shipment.v1.GetShipmentEventsRequest
	(*GetShipmentEventsResponse)(nil), // 9: shipment.v1.GetShipmentEventsResponse
	(*timestamppb.Timestamp)(nil),     // 10: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 11: google.protobuf.Empty
}
var file_shipment_proto_depIdxs = []int32{
	10, // 0: shipment.v1.Shipment.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: shipment.v1.Shipment.status:type_name -> shipment.v1.ShipmentStatus
	10, // 2: shipment.v1.Shipment.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: shipment.v1.ShipmentEvent.status:type_name -> shipment.v1.ShipmentStatus
	10, // 4: shipment.v1.ShipmentEvent.occurred_at:type_name -> google.protobuf.Timestamp
	1,  // 5: shipment.v1.GetShipmentResponse.shipment:type_name -> shipment.v1.Shipment
	0,  // 6: shipment.v1.AddShipmentEventRequest.status:type_name -> shipment.v1.ShipmentStatus
	2,  // 7: shipment.v1.GetShipmentEventsResponse.events:type_name -> shipment.v1.ShipmentEvent
	3,  // 8: shipment.v1.ShipmentService.CreateShipment:input_type -> shipment.v1.CreateShipmentRequest
	5,  // 9: shipment.v1.ShipmentService.GetShipment:input_type -> shipment.v1.GetShipmentRequest
	7,  // 10: shipment.v1.ShipmentService.AddShipmentEvent:input_type -> shipment.v1.AddShipmentEventRequest
	8,  // 11: shipment.v1.ShipmentService.GetShipmentEvents:input_type -> shipment.v1.GetShipmentEventsRequest
	4,  // 12: shipment.v1.ShipmentService.CreateShipment:output_type -> shipment.v1.CreateShipmentResponse
	6,  // 13: shipment.v1.ShipmentService.GetShipment:output_type -> shipment.v1.GetShipmentResponse
	11, // 14: shipment.v1.ShipmentService.AddShipmentEvent:output_type -> google.protobuf.Empty
	9,  // 15: shipment.v1.ShipmentService.GetShipmentEvents:output_type -> shipment.v1.GetShipmentEventsResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_shipment_proto_init() }
func file_shipment_proto_init() {
	if File_shipment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipment_proto_rawDesc), len(file_shipment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipment_proto_goTypes,
		DependencyIndexes: file_shipment_proto_depIdxs,
		EnumInfos:         file_shipment_proto_enumTypes,
		MessageInfos:      file_shipment_proto_msgTypes,
	}.Build()
	File_shipment_proto = out.File
	file_shipment_proto_goTypes = nil
	file_shipment_proto_depIdxs = nil
}
